"""Syn Bank Wallet Twin — Streamlit dashboard.

Four tabs: portfolio summary, client drill-down, opportunity heatmap, and a grounded
AI briefing-note generator (Layer 5 — see CLAUDE.md section 6 and
``prompts/briefing_note_prompt.md`` for the groundedness design).

Reads a single ``wallet_results.csv``-shaped file, currently the DUMMY placeholder
generated by ``src/syn_wallet/generate_dummy_wallet_results.py``. Swap
WALLET_RESULTS_PATH below to the real model output once it exists — the schema is
identical, nothing else in this file needs to change.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

import duckdb
import pandas as pd
import plotly.graph_objects as go
import streamlit as st

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.syn_wallet.generate_briefing_note import build_grounding_context, generate_briefing_note  # noqa: E402

# --- Swap this one line once the real Layers 1-4 model output exists. ---
WALLET_RESULTS_PATH = REPO_ROOT / "data" / "processed" / "wallet_results_DUMMY.csv"
IS_DUMMY = "DUMMY" in WALLET_RESULTS_PATH.name

ENTITY_LOOKUP_SOURCE = REPO_ROOT / "data" / "trade_finance.csv"
COMPETITOR_EVIDENCE_PATH = REPO_ROOT / "data" / "processed" / "competitor_evidence.csv"

PILLAR_LABELS = {
    "cash_mgmt": "Cash Management & Payments",
    "trade_finance": "Trade Finance",
    "fx": "FX / Global Markets",
    "lending_dcm": "Lending & DCM",
}
PILLAR_ORDER = ("cash_mgmt", "trade_finance", "fx", "lending_dcm")
STOCK_PILLARS = {"lending_dcm"}  # a credit-exposure stock, never summed into flow totals

# dataviz skill reference palette — categorical slots 1-4 (blue, orange, aqua, yellow)
PILLAR_COLOR = {
    "cash_mgmt": "#2a78d6",
    "trade_finance": "#eb6834",
    "fx": "#1baf7a",
    "lending_dcm": "#eda100",
}
SEQUENTIAL_BLUE = ["#cde2fb", "#9ec5f4", "#5598e7", "#2a78d6", "#184f95", "#0d366b"]
SURFACE = "#fcfcfb"
INK = "#0b0b0f"
MUTED_INK = "#898781"
GRIDLINE = "#e1e0d9"


@st.cache_data
def load_wallet_results(path: Path) -> pd.DataFrame:
    return pd.read_csv(path)


@st.cache_data
def load_entity_lookup(path: Path) -> pd.DataFrame:
    return duckdb.sql(
        f"SELECT DISTINCT entity_id, entity_name, sector "
        f"FROM read_csv_auto('{path}') ORDER BY entity_name"
    ).df()


@st.cache_data
def load_competitor_evidence(path: Path) -> pd.DataFrame | None:
    if not path.exists():
        return None
    return pd.read_csv(path)


def format_zar(value: float | None) -> str:
    if value is None or pd.isna(value):
        return "—"
    for threshold, suffix in ((1e9, "bn"), (1e6, "m"), (1e3, "k")):
        if abs(value) >= threshold:
            return f"R{value / threshold:,.1f}{suffix}"
    return f"R{value:,.0f}"


def format_pct(value: float | None) -> str:
    return "UNOBSERVABLE" if value is None or pd.isna(value) else f"{value * 100:.1f}%"


def chart_layout(fig: go.Figure, **kwargs) -> go.Figure:
    fig.update_layout(
        plot_bgcolor=SURFACE,
        paper_bgcolor=SURFACE,
        font_color=INK,
        font_family="system-ui, -apple-system, 'Segoe UI', sans-serif",
        margin=dict(l=10, r=10, t=40, b=10),
        transition=dict(duration=450, easing="cubic-in-out"),
        hoverlabel=dict(bgcolor=INK, font_color="#ffffff", bordercolor=INK, font_size=13),
        **kwargs,
    )
    fig.update_xaxes(gridcolor=GRIDLINE, zerolinecolor=GRIDLINE, tickfont_color=MUTED_INK)
    fig.update_yaxes(gridcolor=GRIDLINE, zerolinecolor=GRIDLINE, tickfont_color=MUTED_INK)
    return fig


def confidence_bar(value: float, color: str) -> str:
    pct = max(0.0, min(1.0, float(value))) * 100
    return (
        '<div class="conf-track">'
        f'<div class="conf-fill" style="width:{pct:.0f}%; background:{color};"></div>'
        "</div>"
        f'<div class="conf-caption">Confidence {pct:.0f}%</div>'
    )


def inject_style() -> None:
    st.markdown(
        """
        <style>
        :root {
            --surface: #fcfcfb;
            --ink: #0b0b0f;
            --ink-secondary: #52545c;
            --ink-muted: #898781;
            --border: rgba(11,11,15,0.08);
            --shadow: 0 4px 18px rgba(20,25,40,0.07);
            --shadow-hover: 0 12px 28px rgba(20,25,40,0.14);
            --blue: #2a78d6;
            --orange: #eb6834;
            --aqua: #1baf7a;
            --yellow: #eda100;
        }

        .stApp {
            background: linear-gradient(165deg, #f7f9fc 0%, #eef1f7 45%, #eaf1fb 100%);
            color: var(--ink) !important;
        }
        .stApp p, .stApp span, .stApp li, .stApp label,
        [data-testid="stCaptionContainer"], [data-testid="stCaptionContainer"] p,
        [data-testid="stMarkdownContainer"] p {
            color: var(--ink-secondary) !important;
        }
        [data-testid="stWidgetLabel"] p { color: var(--ink) !important; font-weight: 600; }

        .stApp h1 {
            font-weight: 800 !important;
            letter-spacing: -0.02em;
            background: linear-gradient(90deg, var(--ink) 0%, var(--blue) 55%, var(--aqua) 100%);
            -webkit-background-clip: text;
            background-clip: text;
            color: transparent !important;
            animation: fadeSlideDown .6s ease both;
        }
        .hero-subtitle {
            color: var(--ink-secondary) !important;
            font-size: 0.98rem;
            margin-top: -8px;
            animation: fadeSlideDown .7s ease both;
        }
        .hero-underline {
            height: 4px;
            width: 110px;
            border-radius: 4px;
            margin: 10px 0 22px 0;
            background: linear-gradient(90deg, var(--blue), var(--aqua), var(--orange), var(--yellow));
            background-size: 300% 100%;
            animation: gradientShift 5s ease infinite;
        }

        h2, h3 { color: var(--ink) !important; letter-spacing: -0.01em; }

        @keyframes fadeSlideDown { from {opacity:0; transform: translateY(-10px);} to {opacity:1; transform: translateY(0);} }
        @keyframes fadeSlideUp { from {opacity:0; transform: translateY(16px);} to {opacity:1; transform: translateY(0);} }
        @keyframes gradientShift { 0% {background-position:0% 50%;} 50% {background-position:100% 50%;} 100% {background-position:0% 50%;} }
        @keyframes pulseGlow { 0%,100% {opacity:1;} 50% {opacity:.55;} }

        [data-testid="stMetric"] {
            background: var(--surface);
            border-radius: 14px;
            padding: 14px 18px 10px 18px;
            box-shadow: var(--shadow);
            border: 1px solid var(--border);
            border-top: 3px solid var(--blue);
            transition: transform .25s ease, box-shadow .25s ease;
            animation: fadeSlideUp .55s ease both;
        }
        [data-testid="stMetric"]:hover {
            transform: translateY(-4px);
            box-shadow: var(--shadow-hover);
        }
        [data-testid="stMetricValue"] { font-weight: 700 !important; }
        [data-testid="stMetricLabel"] { color: var(--ink-secondary) !important; font-weight: 600; }

        div[data-testid="column"]:nth-of-type(1) [data-testid="stMetric"] { animation-delay: .04s; border-top-color: var(--blue); }
        div[data-testid="column"]:nth-of-type(2) [data-testid="stMetric"] { animation-delay: .11s; border-top-color: var(--orange); }
        div[data-testid="column"]:nth-of-type(3) [data-testid="stMetric"] { animation-delay: .18s; border-top-color: var(--aqua); }
        div[data-testid="column"]:nth-of-type(4) [data-testid="stMetric"] { animation-delay: .25s; border-top-color: var(--yellow); }

        [data-baseweb="tab-list"] { gap: 6px; }
        [data-baseweb="tab"] {
            border-radius: 10px 10px 0 0 !important;
            font-weight: 600;
            color: var(--ink-secondary) !important;
            transition: background .2s ease, color .2s ease;
        }
        [data-baseweb="tab"] p { color: inherit !important; }
        [data-baseweb="tab"]:hover { background: rgba(42,120,214,0.08); }
        [data-baseweb="tab"][aria-selected="true"] { color: var(--blue) !important; }
        [data-baseweb="tab-highlight"] {
            background-color: var(--blue) !important;
            transition: left .35s cubic-bezier(.4,0,.2,1), width .35s cubic-bezier(.4,0,.2,1) !important;
        }

        [data-testid="stVerticalBlockBorderWrapper"] {
            border-radius: 16px !important;
            box-shadow: var(--shadow);
            transition: box-shadow .3s ease, transform .3s ease;
            animation: fadeSlideUp .5s ease both;
        }
        [data-testid="stVerticalBlockBorderWrapper"]:hover { box-shadow: var(--shadow-hover); }

        [data-testid="stDataFrame"] { border-radius: 12px; overflow: hidden; box-shadow: var(--shadow); }

        .stButton>button {
            border-radius: 10px;
            font-weight: 600;
            transition: transform .15s ease, box-shadow .15s ease;
        }
        .stButton>button:not(:disabled):hover { transform: translateY(-2px); box-shadow: var(--shadow-hover); }

        [data-testid="stAlert"] {
            border-radius: 12px;
            box-shadow: var(--shadow);
            animation: fadeSlideDown .5s ease both;
        }

        .conf-track {
            background: rgba(11,11,15,0.08);
            border-radius: 6px;
            height: 7px;
            overflow: hidden;
            margin-top: 6px;
            width: 100%;
        }
        .conf-fill {
            height: 100%;
            border-radius: 6px;
            width: 0%;
            animation: fillBar 1s cubic-bezier(.22,1,.36,1) forwards;
        }
        @keyframes fillBar { from { width: 0%; } }
        .conf-caption { font-size: 0.72rem; color: var(--ink-muted) !important; margin-top: 3px; }

        @media (max-width: 700px) {
            h1 { font-size: 1.7rem !important; }
            [data-testid="stMetric"] { padding: 10px 12px; }
        }
        </style>
        """,
        unsafe_allow_html=True,
    )


st.set_page_config(page_title="Syn Bank Wallet Twin", page_icon="💠", layout="wide")
inject_style()

if not WALLET_RESULTS_PATH.exists():
    st.error(f"wallet_results file not found: {WALLET_RESULTS_PATH}")
    st.stop()

results = load_wallet_results(WALLET_RESULTS_PATH)
entities = load_entity_lookup(ENTITY_LOOKUP_SOURCE)
results = results.merge(entities, on="entity_id", how="left")
results["pillar_label"] = results["pillar"].map(PILLAR_LABELS)

st.title("Syn Bank — Share of Wallet Intelligence Engine")
st.markdown(
    '<div class="hero-subtitle">Portfolio intelligence across 20 JSE-listed corporate '
    "clients — Cash Management, Trade Finance, FX and Lending & DCM.</div>"
    '<div class="hero-underline"></div>',
    unsafe_allow_html=True,
)

if IS_DUMMY:
    st.warning(
        f"**DUMMY DATA** — reading `{WALLET_RESULTS_PATH.relative_to(REPO_ROOT)}`. "
        "Every number below is a seeded placeholder for UI development, not a real wallet "
        "estimate. Never let these figures reach a slide, the PDF, or a client briefing note.",
        icon="⚠️",
    )

tab_summary, tab_drilldown, tab_heatmap, tab_briefing = st.tabs(
    ["Portfolio Summary", "Client Drill-Down", "Opportunity Heatmap", "AI Briefing Notes"]
)

# ---------------------------------------------------------------------------
# Tab 1 — Portfolio summary
# ---------------------------------------------------------------------------
with tab_summary:
    st.caption(
        "Addressable activity is never summed across pillars — Cash Management, Trade "
        "Finance and FX are three separate flow measures, and Lending & DCM is a credit-"
        "exposure stock, not a flow. Each pillar is shown on its own scale."
    )

    pillar_totals = (
        results.groupby(["pillar", "pillar_label"], as_index=False)
        .agg(addressable_p50=("addressable_p50", "sum"), observed=("observed", "sum"))
    )

    cols = st.columns(len(PILLAR_ORDER), gap="medium")
    for col, pillar in zip(cols, PILLAR_ORDER):
        row = pillar_totals[pillar_totals["pillar"] == pillar].iloc[0]
        label = PILLAR_LABELS[pillar]
        with col:
            if pillar in STOCK_PILLARS:
                st.metric(f"{label} (exposure)", format_zar(row["addressable_p50"]))
                st.caption("Unobservable internally — see client drill-down.")
            else:
                share = row["observed"] / row["addressable_p50"] if row["addressable_p50"] else None
                st.metric(f"{label} (annual, addressable)", format_zar(row["addressable_p50"]))
                st.caption(f"Observed: {format_zar(row['observed'])} ({format_pct(share)} share)")

    st.write("")
    with st.container(border=True):
        st.subheader("Addressable activity by pillar (portfolio total, P50)")
        fig = go.Figure()
        for pillar in PILLAR_ORDER:
            row = pillar_totals[pillar_totals["pillar"] == pillar].iloc[0]
            fig.add_bar(
                x=[PILLAR_LABELS[pillar]],
                y=[row["addressable_p50"]],
                marker_color=PILLAR_COLOR[pillar],
                marker_line_width=0,
                name=PILLAR_LABELS[pillar],
                showlegend=False,
                text=[format_zar(row["addressable_p50"])],
                textposition="outside",
                textfont=dict(color=INK, size=13),
                hovertemplate=f"{PILLAR_LABELS[pillar]}<br>%{{y:,.0f}} ZAR<extra></extra>",
            )
        chart_layout(fig, height=380, yaxis_title="ZAR (P50)", bargap=0.35)
        st.plotly_chart(fig, width="stretch", config={"displayModeBar": False})

    st.write("")
    with st.container(border=True):
        st.subheader("Top 10 growth opportunities")
        top10 = results.sort_values("rank").head(10)[
            ["rank", "entity_name", "sector", "pillar_label", "addressable_p50", "observed",
             "unaddressed_p50", "confidence", "opportunity_score"]
        ].copy()
        for col in ("addressable_p50", "observed", "unaddressed_p50"):
            top10[col] = top10[col].apply(format_zar)
        top10["opportunity_score"] = top10["opportunity_score"].round(3)
        top10.columns = ["Rank", "Client", "Sector", "Pillar", "Addressable (P50)", "Observed",
                          "Unaddressed (P50)", "Confidence", "Opportunity Score"]
        st.dataframe(
            top10,
            hide_index=True,
            width="stretch",
            column_config={
                "Confidence": st.column_config.ProgressColumn(
                    "Confidence", min_value=0.0, max_value=1.0, format="%.2f"
                ),
                "Opportunity Score": st.column_config.ProgressColumn(
                    "Opportunity Score", min_value=0.0, max_value=1.0, format="%.2f"
                ),
            },
        )

# ---------------------------------------------------------------------------
# Tab 2 — Client drill-down
# ---------------------------------------------------------------------------
with tab_drilldown:
    entity_name = st.selectbox("Client", entities["entity_name"].tolist())
    entity_id = entities.loc[entities["entity_name"] == entity_name, "entity_id"].iloc[0]
    sector = entities.loc[entities["entity_name"] == entity_name, "sector"].iloc[0]
    st.caption(f"{entity_id} · {sector}")

    client_rows = results[results["entity_id"] == entity_id].set_index("pillar")

    metric_cols = st.columns(len(PILLAR_ORDER), gap="medium")
    for col, pillar in zip(metric_cols, PILLAR_ORDER):
        if pillar not in client_rows.index:
            continue
        row = client_rows.loc[pillar]
        with col:
            st.metric(PILLAR_LABELS[pillar], format_zar(row["addressable_p50"]))
            st.caption(f"Share: {format_pct(row['share_p50'])}")
            st.markdown(confidence_bar(row["confidence"], PILLAR_COLOR[pillar]), unsafe_allow_html=True)

    st.write("")
    with st.container(border=True):
        st.subheader("Addressable range (P10–P90) vs. observed, by pillar")
        fig = go.Figure()
        for i, pillar in enumerate(PILLAR_ORDER):
            if pillar not in client_rows.index:
                continue
            row = client_rows.loc[pillar]
            fig.add_shape(
                type="line", x0=i, x1=i, y0=row["addressable_p10"], y1=row["addressable_p90"],
                line=dict(color=PILLAR_COLOR[pillar], width=10), opacity=0.35,
            )
            fig.add_trace(go.Scatter(
                x=[i], y=[row["addressable_p50"]], mode="markers",
                marker=dict(color=PILLAR_COLOR[pillar], size=14, symbol="line-ew", line_width=3),
                name="Addressable P50", showlegend=(i == 0),
                hovertemplate=f"Addressable P50: {format_zar(row['addressable_p50'])}<extra></extra>",
            ))
            if pd.notna(row["observed"]):
                fig.add_trace(go.Scatter(
                    x=[i], y=[row["observed"]], mode="markers",
                    marker=dict(color=INK, size=10, symbol="diamond"),
                    name="Observed (Syn Bank)", showlegend=(i == 0),
                    hovertemplate=f"Observed: {format_zar(row['observed'])}<extra></extra>",
                ))
            else:
                fig.add_annotation(x=i, y=row["addressable_p10"], text="unobservable",
                                    showarrow=False, yshift=-16, font=dict(color=MUTED_INK, size=11))
        fig.update_xaxes(tickmode="array", tickvals=list(range(len(PILLAR_ORDER))),
                          ticktext=[PILLAR_LABELS[p] for p in PILLAR_ORDER])
        chart_layout(fig, height=440, legend=dict(orientation="h", y=1.12))
        st.plotly_chart(fig, width="stretch", config={"displayModeBar": False})

# ---------------------------------------------------------------------------
# Tab 3 — Opportunity heatmap
# ---------------------------------------------------------------------------
with tab_heatmap:
    with st.container(border=True):
        st.caption(
            "Opportunity score (0.5·unaddressed + 0.3·confidence + 0.2·propensity), "
            "normalised within each pillar."
        )

        pivot = results.pivot(index="entity_name", columns="pillar", values="opportunity_score")
        pivot = pivot[list(PILLAR_ORDER)]
        order = pivot.mean(axis=1).sort_values(ascending=False).index
        pivot = pivot.loc[order]

        fig = go.Figure(data=go.Heatmap(
            z=pivot.values,
            x=[PILLAR_LABELS[p] for p in pivot.columns],
            y=pivot.index,
            colorscale=[[i / (len(SEQUENTIAL_BLUE) - 1), c] for i, c in enumerate(SEQUENTIAL_BLUE)],
            xgap=3,
            ygap=3,
            hovertemplate="%{y} · %{x}<br>Opportunity score: %{z:.2f}<extra></extra>",
            colorbar=dict(title="Score", thickness=14),
        ))
        chart_layout(fig, height=680, yaxis=dict(autorange="reversed"))
        st.plotly_chart(fig, width="stretch", config={"displayModeBar": False})

# ---------------------------------------------------------------------------
# Tab 4 — AI briefing notes (Layer 5, grounded generation)
# ---------------------------------------------------------------------------
with tab_briefing:
    with st.container(border=True):
        st.caption(
            "Grounded call-prep briefing note (5-6 sentences), generated only from the computed "
            "tables shown below — no free generation. The exact JSON context sent to the model "
            "is displayed alongside the note so every sentence can be checked against it."
        )
        briefing_entity_name = st.selectbox("Client", entities["entity_name"].tolist(), key="briefing_client")
        briefing_entity_id = entities.loc[entities["entity_name"] == briefing_entity_name, "entity_id"].iloc[0]
        briefing_sector = entities.loc[entities["entity_name"] == briefing_entity_name, "sector"].iloc[0]

        competitor_evidence = load_competitor_evidence(COMPETITOR_EVIDENCE_PATH)
        context = build_grounding_context(
            briefing_entity_id, results, briefing_entity_name, briefing_sector, competitor_evidence
        )

        api_key_present = bool(os.environ.get("ANTHROPIC_API_KEY"))
        generate_clicked = st.button("Generate briefing note", disabled=not api_key_present)
        if not api_key_present:
            st.info(
                "Set ANTHROPIC_API_KEY in the environment to enable live generation. The grounding "
                "context below is exactly what would be sent — nothing else."
            )

        if generate_clicked:
            import anthropic

            with st.spinner("Generating grounded briefing note..."):
                try:
                    note = generate_briefing_note(context, anthropic.Anthropic())
                    st.success(note)
                except Exception as exc:  # noqa: BLE001 - surface any API/config error directly to the demo user
                    st.error(f"Briefing note generation failed: {exc}")

        with st.expander("Grounding context sent to the model", expanded=not api_key_present):
            st.json(context)
