"""Generate ``COMMERCIAL_INTELLIGENCE_REPORT.md`` from the intelligence outputs.

    .venv/bin/python -m src.syn_wallet.build_wallet --overwrite --sensitivity
    .venv/bin/python -m src.syn_wallet.build_intelligence --overwrite
    .venv/bin/python -m analysis.commercial_intelligence_report

Every figure is read back from ``data/processed/*.parquet``. The report cannot
claim a rule the layer does not apply or a number it did not produce.
"""

from __future__ import annotations

import json

import pandas as pd

from src.syn_wallet import config as paths
from src.syn_wallet.intelligence import config
from src.syn_wallet.wallet import assumptions

from .report_common import connect, table, write

REPORT_PATH = paths.REPOSITORY_ROOT / "COMMERCIAL_INTELLIGENCE_REPORT.md"

TABLES = (
    "client_opportunity_intelligence",
    "portfolio_opportunity_intelligence",
    "banker_questions",
    "opportunity_explanations",
    "client_opportunity_cards",
    "opportunity_selection_detail",
    "opportunity_sensitivity_summary",
    "opportunity_engine",
)

#: Clients whose full profile is reproduced. Chosen to span the three situations
#: a reviewer most needs to see: the largest and best-evidenced opportunity in
#: the book, the one client whose primary is not cash management, and a client
#: whose headline figure is benchmark-sensitive.
REPRESENTATIVE = ("E02", "E16", "E17")

PRODUCT_SORT = (
    "CASE product WHEN 'cash_management' THEN 1 WHEN 'fx_global_markets' THEN 2 "
    "WHEN 'trade_finance' THEN 3 WHEN 'lending' THEN 4 ELSE 5 END"
)


def build_report() -> str:
    connection = connect(TABLES)
    report = json.loads(
        (paths.PROCESSED_DIR / "intelligence_report.json").read_text(encoding="utf-8")
    )
    sections: list[str] = []
    add = sections.append

    add("# Syn Bank — Commercial Intelligence Report\n")
    add(
        f"`{report['intelligence_version']}` on analytical contract "
        f"`{report['methodology_version']}`. {report['clients']} clients x "
        f"{len(report['products'])} pillars. "
        f"{report['explanations_generated']} explanations and "
        f"{report['questions_generated']} banker questions, all generated deterministically — "
        "no LLM is called anywhere in this layer, and identical inputs always produce identical "
        "words.\n"
    )
    add(
        "This is the **semantic layer**: it turns the wallet model's output into something a "
        "Corporate & Investment Banking relationship manager can act on. It adds no data. Every "
        "number in every sentence is read from `opportunity_engine.parquet`, and every range "
        "from `model_sensitivity.parquet`.\n"
    )
    add(
        "Generated by `analysis/commercial_intelligence_report.py`. Not hand-edited. Companion "
        "documents: `MODEL_FINAL_REPORT.md` (the analytical contract), `MODEL_SENSITIVITY.md` "
        "(the 36-scenario sweep).\n"
    )

    # ==================================================== 1. Terminology rules
    add("## 1. Terminology rules\n")
    add(
        "The wrong noun is a commercial misstatement, so the vocabulary is enforced in code "
        "rather than left to the writer. Every generated string is checked against a list of "
        "forbidden phrases by a test that fails the build.\n"
    )
    terminology = pd.DataFrame(
        [
            {
                "Pillar": assumptions.PRODUCT_LABELS[product],
                "Class": report["product_classes"][product],
                "The rand figure is called": config.DENOMINATOR_LABEL[product],
                "Share of wallet?": (
                    "yes" if product in assumptions.WALLET_PILLARS else "**never**"
                ),
            }
            for product in assumptions.PRODUCTS
        ]
    )
    add(table(terminology))
    add(
        "**Forbidden anywhere in generated text:** "
        + ", ".join(f"`{phrase}`" for phrase in config.FORBIDDEN_PHRASES)
        + ".\n"
    )
    add(
        "> The one that matters most: **Addressable Cash Flow is the client's own operating "
        "turnover, not bank income.** R14.31tn of portfolio addressable cash flow is money "
        "twenty companies must move through some bank. It is not a fee pool, and no fee figure "
        "is estimated on it, because Syn Bank discloses no pricing.\n"
    )
    add(
        "**Lending** is a *financing opportunity* and never receives share-of-wallet language: "
        "Syn Bank's data contains no loan book, so there is no observed numerator to divide. "
        "**Investment banking** is an *opportunity signal* and never receives a rand figure.\n"
    )

    # ============================================== 2. Recommendation logic
    add("## 2. Recommendation logic\n")
    add("### 2.1 Selecting the primary opportunity\n")
    add(
        "The naive answer is *the biggest rand number*, and it is wrong. The five pillars produce "
        "rand on incomparable bases, and their evidence quality differs by a factor of three. So "
        "selection multiplies the model's commercial score by what is known about it:\n"
    )
    add(
        "```\n"
        "selection_score = commercial_opportunity_score\n"
        f"                x role_weight        CORE {config.ROLE_WEIGHT[assumptions.CORE]:.2f}"
        f" / SUPPORTING {config.ROLE_WEIGHT[assumptions.SUPPORTING]:.2f}"
        f" / SIGNAL_ONLY {config.ROLE_WEIGHT[assumptions.SIGNAL_ONLY]:.2f}\n"
        f"                x confidence_weight  HIGH {config.CONFIDENCE_WEIGHT['HIGH']:.2f}"
        f" / MEDIUM {config.CONFIDENCE_WEIGHT['MEDIUM']:.2f}"
        f" / LOW {config.CONFIDENCE_WEIGHT['LOW']:.2f}\n"
        f"                x (1 - {config.HIGH_SEVERITY_PENALTY:.2f} if a HIGH-severity "
        "diagnostic is open)\n"
        f"                x (1 - {config.SENSITIVITY_PENALTY:.2f} if the estimate is "
        "benchmark-sensitive)\n"
        "```\n"
    )
    add(
        "Worked through on the brief's own example: a LOW-confidence FX row scoring 0.75 lands "
        f"at `0.75 x 1.00 x {config.CONFIDENCE_WEIGHT['LOW']:.2f} = "
        f"{0.75 * config.CONFIDENCE_WEIGHT['LOW']:.2f}`. A HIGH-confidence lending row scoring "
        f"0.60 lands at `0.60 x {config.ROLE_WEIGHT[assumptions.SUPPORTING]:.2f} x 1.00 = "
        f"{0.60 * config.ROLE_WEIGHT[assumptions.SUPPORTING]:.2f}` and wins, whatever the rand "
        "amounts are. A test asserts it.\n"
    )
    add(
        "Three slots per client. **Primary** is the highest selection score among pillars that "
        "demonstrated headroom. **Secondary** is the next. **Supporting signal** is the "
        "highest-scoring remaining pillar that is SUPPORTING or SIGNAL_ONLY class, or is not "
        "HIGH confidence — the slot deliberately prefers softer evidence, so the conversation "
        "carries the caveated material rather than three confident numbers.\n"
    )

    add("### 2.2 Opportunity status\n")
    add(
        "```\n"
        "1. rand pillar with headroom below "
        f"{config.MIN_HEADROOM_FRACTION:.0%} of addressable  -> NO_HEADROOM_DEMONSTRATED\n"
        "2. SIGNAL_ONLY pillar                                    -> MONITOR (cannot rise higher)\n"
        f"3. HIGH confidence + score >= {config.PRIORITY_MIN_SCORE:.2f} + no HIGH-severity "
        "flag  -> PRIORITY\n"
        f"4. score >= {config.INVESTIGATE_MIN_SCORE:.2f} and not LOW confidence"
        "                    -> INVESTIGATE\n"
        "5. everything else                                       -> MONITOR\n"
        "```\n"
    )
    statuses = pd.DataFrame(
        [
            {
                "Status": status,
                "Banker action": config.STATUS_ACTION[status],
                "Client x product rows": report["status_counts"].get(status, 0),
                "Meaning": config.STATUS_NOTE[status],
            }
            for status in config.STATUS_ORDER
        ]
    )
    add(table(statuses))
    add(
        "> **A LOW-confidence opportunity can never reach PRIORITY.** No combination of size and "
        f"score promotes it: `PRIORITY_REQUIRED_BAND = {config.PRIORITY_REQUIRED_BAND}`. The only "
        "route is a named entry in `PRIORITY_OVERRIDES` carrying a written reason — a decision a "
        f"person makes and signs. The shipped registry is empty "
        f"({len(config.PRIORITY_OVERRIDES)} entries), and a test asserts both the rule and the "
        "emptiness.\n"
    )

    # ============================================ 3. Portfolio opportunity summary
    add("## 3. Portfolio opportunity summary\n")
    position = connection.execute(
        f"""
        SELECT product_label AS "Pillar",
               MAX(CASE WHEN metric = 'observed_zar' THEN value_text END) AS "Observed",
               MAX(CASE WHEN metric = 'addressable_zar' THEN value_text END) AS "Addressable",
               MAX(CASE WHEN metric = 'opportunity_zar' THEN value_text END) AS "Opportunity",
               COALESCE(MAX(CASE WHEN metric = 'value_weighted_share' THEN value_text END),
                        'no share') AS "Share",
               COALESCE(MAX(CASE WHEN metric = 'opportunity_range_text' THEN value_text END), '')
                 AS "Range across 36 scenarios"
        FROM portfolio_opportunity_intelligence
        WHERE section = 'portfolio_position' AND product IS NOT NULL
        GROUP BY product, product_label
        HAVING "Observed" IS NOT NULL OR "Opportunity" IS NOT NULL
        ORDER BY {PRODUCT_SORT}
        """
    ).df()
    add(table(position))
    add(
        "> **These rows must never be added.** Two of the pillars overlap on the SWIFT channel by "
        "an amount the supplied data cannot resolve, and the five bases are not commensurable. "
        "There is no total, no output produces one, and a build-time assertion prevents one "
        "appearing.\n"
    )
    ib_categories = connection.execute(
        """
        SELECT regexp_extract(note, 'Category `([^`]+)`', 1) AS "Category",
               value_text AS "Clients"
        FROM portfolio_opportunity_intelligence
        WHERE metric = 'ib_signal_category_clients' ORDER BY value_numeric DESC
        """
    ).df()
    add("Investment-banking signal distribution (no rand figure exists for this pillar):\n")
    add(table(ib_categories))

    # =================================================== 4. Top opportunities
    add("## 4. Top opportunities\n")
    add("### 4.1 By client, on the primary slot\n")
    top_clients = connection.execute(
        """
        SELECT CAST(rank AS INTEGER) AS "#", entity_name AS "Client", sector AS "Sector",
               product_label AS "Primary pillar", value_text AS "Opportunity",
               printf('%.3f', value_numeric) AS "Selection score", note AS "Status"
        FROM portfolio_opportunity_intelligence
        WHERE section = 'top_by_client' ORDER BY rank
        """
    ).df()
    add(table(top_clients))

    add("### 4.2 By pillar\n")
    top_products = connection.execute(
        f"""
        SELECT product_label AS "Pillar", CAST(rank AS INTEGER) AS "#", entity_name AS "Client",
               value_text AS "Opportunity", printf('%.3f', value_numeric) AS "Selection score",
               note AS "Status and confidence"
        FROM portfolio_opportunity_intelligence
        WHERE section = 'top_by_product' AND rank <= 3
        ORDER BY {PRODUCT_SORT}, rank
        """
    ).df()
    add(table(top_products))

    add("### 4.3 Where the primary slot concentrates\n")
    concentration = connection.execute(
        """
        SELECT product_label AS "Pillar", value_text AS "Clients", note AS "Share of portfolio"
        FROM portfolio_opportunity_intelligence
        WHERE section = 'primary_concentration' AND metric = 'clients_with_this_primary'
        ORDER BY rank
        """
    ).df()
    add(table(concentration))
    warning = connection.execute(
        "SELECT note FROM portfolio_opportunity_intelligence "
        "WHERE metric = 'concentration_warning'"
    ).fetchone()
    if warning:
        add(f"> {warning[0]}\n")

    add("### 4.4 Clients with several simultaneous opportunities\n")
    multiple = connection.execute(
        """
        SELECT entity_name AS "Client", sector AS "Sector",
               CAST(value_numeric AS INTEGER) AS "Pillars at PRIORITY or INVESTIGATE",
               value_text AS "Which"
        FROM portfolio_opportunity_intelligence
        WHERE section = 'multiple_opportunities'
        ORDER BY value_numeric DESC, entity_name
        """
    ).df()
    add(table(multiple))
    add(
        "Breadth of opportunity, not a combined figure. The pillars are counted, never summed.\n"
    )

    # ================================================== 5. Confidence overview
    add("## 5. Confidence overview\n")
    confidence = connection.execute(
        f"""
        SELECT product_label AS "Pillar",
               MAX(CASE WHEN metric = 'product_class' THEN value_text END) AS "Class",
               MAX(CASE WHEN metric = 'mean_confidence' THEN value_text END) AS "Mean confidence",
               MAX(CASE WHEN metric = 'status_priority_count' THEN value_text END) AS "PRIORITY",
               MAX(CASE WHEN metric = 'status_investigate_count' THEN value_text END)
                 AS "INVESTIGATE",
               MAX(CASE WHEN metric = 'status_monitor_count' THEN value_text END) AS "MONITOR",
               MAX(CASE WHEN metric = 'status_no_headroom_demonstrated_count' THEN value_text END)
                 AS "NO HEADROOM"
        FROM portfolio_opportunity_intelligence
        WHERE section = 'product_metrics'
        GROUP BY product, product_label ORDER BY {PRODUCT_SORT}
        """
    ).df()
    add(table(confidence))
    bands = connection.execute(
        f"""
        SELECT product_label AS "Pillar",
               MAX(CASE WHEN metric = 'clients_high' THEN value_text END) AS "HIGH",
               MAX(CASE WHEN metric = 'clients_medium' THEN value_text END) AS "MEDIUM",
               MAX(CASE WHEN metric = 'clients_low' THEN value_text END) AS "LOW"
        FROM portfolio_opportunity_intelligence
        WHERE section = 'confidence_distribution'
        GROUP BY product, product_label ORDER BY {PRODUCT_SORT}
        """
    ).df()
    add(table(bands))
    add(
        "> The confidence spread is what drives the whole selection logic. Cash management is the "
        "only pillar with HIGH confidence across most of the portfolio, which is why it wins the "
        "primary slot so often — and why FX, despite carrying the second-largest rand figures, "
        "rarely does.\n"
    )

    add("### Large opportunities on weak evidence\n")
    add(
        "The rows most likely to be quoted and least likely to survive scrutiny. Every one is "
        "capped at MONITOR by the status rules.\n"
    )
    risky = connection.execute(
        """
        SELECT CAST(rank AS INTEGER) AS "#", entity_name AS "Client", product_label AS "Pillar",
               value_text AS "Opportunity", note AS "Why it is capped"
        FROM portfolio_opportunity_intelligence
        WHERE section = 'low_confidence_high_value' AND rank <= 6 ORDER BY rank
        """
    ).df()
    add(table(risky))

    # ================================================= 6. Sensitivity overview
    add("## 6. Sensitivity overview\n")
    add(
        f"Every rand estimate is tested across {report['scenarios_tested']} model runs. The "
        "layer publishes `estimate_low`, `estimate_base`, `estimate_high`, `rank_stability` and "
        "`sensitivity_flag` per client x pillar, and the wording of every explanation changes "
        "with them.\n"
    )
    sensitivity = connection.execute(
        f"""
        SELECT s.product AS "Pillar",
               COUNT(*) FILTER (WHERE s.sensitivity_flag = 'STABLE') AS "Stable",
               COUNT(*) FILTER (WHERE s.sensitivity_flag = 'MODERATE') AS "Moderate",
               COUNT(*) FILTER (WHERE s.sensitivity_flag = 'SENSITIVE') AS "Sensitive",
               COUNT(*) FILTER (WHERE s.sensitivity_flag = 'NOT_APPLICABLE') AS "No rand figure",
               COUNT(*) FILTER (WHERE s.rank_stability = 'SENSITIVE') AS "Unstable rank"
        FROM opportunity_sensitivity_summary s
        GROUP BY s.product ORDER BY {PRODUCT_SORT.replace('product', 's.product')}
        """
    ).df()
    add(table(sensitivity))
    add(
        "Wording is driven by the flag, not chosen: a STABLE estimate is described as *stable "
        "across tested assumptions*; a SENSITIVE one carries *the model indicates potential "
        "headroom, but the estimate is benchmark-sensitive* together with its explicit range. "
        "This is never hidden from the reader.\n"
    )
    widest = connection.execute(
        """
        SELECT e.entity_name AS "Client", s.product AS "Pillar",
               zar(s.estimate_low) AS "Low", zar(s.estimate_base) AS "Base",
               zar(s.estimate_high) AS "High",
               printf('%.0f%%', 100 * s.estimate_range_pct) AS "Range",
               s.rank_stability AS "Rank stability"
        FROM opportunity_sensitivity_summary s
        JOIN (SELECT DISTINCT entity_id, entity_name FROM opportunity_engine) e
          ON e.entity_id = s.entity_id
        WHERE s.estimate_range_pct IS NOT NULL
        ORDER BY s.estimate_range_pct DESC LIMIT 8
        """
    ).df()
    add("The widest ranges in the book:\n")
    add(table(widest))

    # ============================================ 7. Representative profiles
    add("## 7. Representative client profiles\n")
    for entity_id in REPRESENTATIVE:
        profile = connection.execute(
            f"SELECT * FROM client_opportunity_intelligence WHERE entity_id = '{entity_id}'"
        ).df()
        if profile.empty:
            continue
        row = profile.iloc[0]
        add(f"### {row['entity_id']} {row['entity_name']} — {row['sector']}, {row['fy_label']}\n")
        add(f"> {row['opportunity_summary']}\n")
        pillars = connection.execute(
            f"""
            SELECT product_label AS "Pillar", product_class AS "Class",
                   CASE WHEN observed_zar IS NULL THEN 'n/a' ELSE zar(observed_zar) END
                     AS "Observed",
                   CASE WHEN addressable_zar IS NULL THEN 'n/a' ELSE zar(addressable_zar) END
                     AS "Addressable",
                   CASE WHEN share IS NULL THEN 'no share' ELSE printf('%.2f%%', 100 * share) END
                     AS "Share",
                   CASE WHEN opportunity_zar IS NULL THEN 'signal only'
                        ELSE zar(opportunity_zar) END AS "Opportunity",
                   confidence_band AS "Confidence", opportunity_status AS "Status",
                   COALESCE(selection_slot, '') AS "Slot"
            FROM opportunity_selection_detail
            WHERE entity_id = '{entity_id}' ORDER BY {PRODUCT_SORT}
            """
        ).df()
        add(table(pillars))
        primary = connection.execute(
            f"""
            SELECT narrative FROM opportunity_explanations
            WHERE entity_id = '{entity_id}' AND selection_slot = 'primary'
            """
        ).fetchone()
        if primary:
            add("**Primary opportunity explanation:**\n")
            add("```\n" + primary[0] + "\n```\n")

    # ============================================= 8. Example banker questions
    add("## 8. Example banker questions\n")
    add(
        f"{report['questions_generated']} questions across {report['clients']} clients — up to "
        "four for the primary opportunity, one for the secondary. Every one is parameterised by "
        "figures from that client's own row; a question that cannot be filled with real numbers "
        "is not emitted.\n"
    )
    for entity_id in REPRESENTATIVE:
        asked = connection.execute(
            f"""
            SELECT q.question_index AS "#", q.product AS "Pillar", q.question AS "Question"
            FROM banker_questions q
            WHERE q.entity_id = '{entity_id}' AND q.selection_slot = 'primary'
            ORDER BY q.question_index
            """
        ).df()
        if asked.empty:
            continue
        name = connection.execute(
            f"SELECT entity_name FROM banker_questions WHERE entity_id = '{entity_id}' LIMIT 1"
        ).fetchone()[0]
        add(f"**{entity_id} {name}**\n")
        add(table(asked))

    # =========================================== 9. Dashboard-safe metrics
    add("## 9. Dashboard-safe metrics\n")
    add(
        "Published in `portfolio_opportunity_intelligence.parquet` as a long table — "
        "`section, metric, product, sector, entity_id, rank, value_numeric, value_text, note` — "
        "so a dashboard filters to one section and renders it without knowing anything else "
        "about this layer.\n"
    )
    sections_table = connection.execute(
        """
        SELECT section AS "Section", COUNT(*) AS "Rows",
               COUNT(DISTINCT metric) AS "Distinct metrics"
        FROM portfolio_opportunity_intelligence GROUP BY section ORDER BY section
        """
    ).df()
    add(table(sections_table))
    add("### Product-level metrics\n")
    product_metrics = connection.execute(
        f"""
        SELECT product_label AS "Pillar",
               MAX(CASE WHEN metric = 'median_client_share' THEN value_text END) AS "Median share",
               MAX(CASE WHEN metric = 'value_weighted_share' THEN value_text END)
                 AS "Value-weighted share",
               MAX(CASE WHEN metric = 'mean_confidence' THEN value_text END) AS "Confidence",
               MAX(CASE WHEN metric = 'opportunity_count' THEN value_text END)
                 AS "Opportunities",
               MAX(CASE WHEN metric = 'high_confidence_opportunity_count' THEN value_text END)
                 AS "High-confidence",
               MAX(CASE WHEN metric = 'sensitivity_level' THEN value_text END) AS "Sensitivity"
        FROM portfolio_opportunity_intelligence WHERE section = 'product_metrics'
        GROUP BY product, product_label ORDER BY {PRODUCT_SORT}
        """
    ).df()
    add(table(product_metrics))
    add("### Client-level card\n")
    add(
        "`client_opportunity_cards.parquet` is the compact list view: primary opportunity, its "
        "score, confidence, headroom, sensitivity and next action, one row per client. The top "
        "of that list:\n"
    )
    cards = connection.execute(
        """
        SELECT entity_name AS "Client", primary_opportunity AS "Primary opportunity",
               printf('%.3f', primary_opportunity_score) AS "Score",
               confidence_band AS "Confidence",
               printf('%.0f%%', 100 * headroom) AS "Headroom",
               sensitivity AS "Sensitivity", status AS "Status", next_action AS "Next action"
        FROM client_opportunity_cards ORDER BY primary_opportunity_score DESC LIMIT 8
        """
    ).df()
    add(table(cards))

    # ============================================= 10. Outputs
    add("## 10. Outputs\n")
    add(
        "| File | Grain | Contents |\n"
        "|---|---|---|\n"
        "| `client_opportunity_intelligence.parquet` | 20 rows | The full client profile: every "
        "pillar side by side, all three selected slots, confidence per pillar, sensitivity per "
        "pillar, and a one-sentence summary |\n"
        "| `portfolio_opportunity_intelligence.parquet` | long | Twelve sections of portfolio "
        "intelligence and dashboard-safe metrics |\n"
        "| `banker_questions.parquet` | "
        f"{report['questions_generated']} rows | Client-specific questions with the fields each "
        "was built from |\n"
        "| `opportunity_explanations.parquet` | "
        f"{report['explanations_generated']} rows | Six-part explanations for every client x "
        "pillar |\n"
        "| `client_opportunity_cards.parquet` | 20 rows | The compact list view |\n"
        "| `opportunity_selection_detail.parquet` | 100 rows | Every selection factor, status and "
        "reason, so any ranking decision can be re-derived |\n"
        "| `opportunity_sensitivity_summary.parquet` | 100 rows | Base, low, high, range, rank "
        "stability and flag per client x pillar |\n"
    )
    add(
        "The first four are also written as JSON with the same records, NaN rendered as `null`, "
        "ready for an API or dashboard to serve directly.\n"
    )

    add("## 11. What this layer does not do\n")
    add(
        "- **No LLM.** Every sentence is a template filled from a published field. The same "
        "inputs always produce the same words, and a test asserts it.\n"
        "- **No new numbers.** The only inputs are `opportunity_engine.parquet`, "
        "`client_opportunity_profile.parquet` and `model_sensitivity.parquet`. Nothing is "
        "recomputed from the underlying model.\n"
        "- **No cross-pillar total.** Not in any table, not in any sentence.\n"
        "- **No ownership claim.** An opportunity is addressable activity not observed in Syn "
        "Bank's data — never business a competitor holds, never revenue lost, never revenue "
        "confirmed.\n"
        "- **No dashboard.** That is the next stage, and it should read these tables.\n"
    )
    add("## 12. Reproduce\n")
    add(
        "```bash\n"
        ".venv/bin/python -m src.syn_wallet.build_wallet --overwrite --sensitivity\n"
        ".venv/bin/python -m src.syn_wallet.build_intelligence --overwrite\n"
        ".venv/bin/python -m analysis.commercial_intelligence_report\n"
        ".venv/bin/python -m pytest\n"
        "```\n"
    )

    connection.close()
    return "\n".join(sections)


def main() -> None:
    write(REPORT_PATH, build_report())


if __name__ == "__main__":
    main()
