"""Generate ``docs/GENAI_DESIGN.md`` from the copilot's own configuration and outputs.

    .venv/bin/python -m analysis.genai_design_report

Figures in the document -- context sizes, routing coverage, demo answers stored,
test counts -- are measured by running the deterministic half of the copilot,
not typed in.
"""

from __future__ import annotations

import json
import pandas as pd

from src.syn_wallet import config as paths
from src.syn_wallet.copilot import config, router, validation
from src.syn_wallet.copilot.demos import DemoLibrary
from src.syn_wallet.copilot.engine import Copilot
from src.syn_wallet.copilot.retrieval import REQUIRED_TABLES

from .report_common import table, write

REPORT_PATH = paths.REPOSITORY_ROOT / "docs" / "GENAI_DESIGN.md"

#: One example per supported use case, in the brief's own wording, measured live.
USE_CASES = (
    ("Client briefing", "Prepare a briefing for Shoprite."),
    ("Opportunity explanation", "Why is Vodacom flagged for an FX opportunity?"),
    ("Portfolio query", "Which clients have the largest high-confidence opportunities?"),
    ("Product query", "Which mining clients have the strongest trade-finance opportunities?"),
    ("Sensitivity question", "How reliable is the Vodacom FX opportunity?"),
    ("Meeting preparation", "What should the banker ask MTN about?"),
    ("Executive summary", "Summarize the top five opportunities in the portfolio."),
    ("Methodology question", "How does the model calculate addressable cash flow?"),
)


def build_report() -> str:
    copilot = Copilot.from_processed()
    library = DemoLibrary.from_processed(paths.PROCESSED_DIR)
    sections: list[str] = []
    add = sections.append

    add("# Syn Bank Client Opportunity Copilot — Design\n")
    add(
        f"`{config.COPILOT_VERSION}` on prompt `{config.PROMPT_VERSION}`, over commercial "
        "intelligence `intelligence-1.0.0` and analytical contract `wallet-1.1.0`. Default "
        f"provider `deepseek`, default model `{config.DEFAULT_MODEL}`.\n"
    )
    add(
        "Generated by `analysis/genai_design_report.py`. The actual prompts are in "
        "`docs/GENAI_PROMPTS.md`, generated from the same module the system sends.\n"
    )

    # ================================================================= Purpose
    add("## 1. What it is for\n")
    add(
        "One question, asked by a Corporate & Investment Banking relationship manager:\n\n"
        "> Which client should I focus on, for which product, why does the system believe it, "
        "how strong is the evidence, and what should I investigate next?\n"
    )
    add(
        "The copilot answers it in the banker's own language. It does **not** compute anything. "
        "Four deterministic stages already did that, and this layer's entire job is the last "
        "mile of presentation.\n"
    )

    # ============================================================ Architecture
    add("## 2. Architecture\n")
    add(
        "```\n"
        "  stage 1-2   raw CSV -> cleaned Parquet -> client feature table\n"
        "  stage 3     wallet model          -> opportunity_engine.parquet\n"
        "                                       client_opportunity_profile.parquet\n"
        "  stage 4     commercial intelligence -> client_opportunity_intelligence\n"
        "                                        opportunity_explanations\n"
        "                                        banker_questions\n"
        "                                        portfolio_opportunity_intelligence\n"
        "  ------------------------------------------------------------------\n"
        "  stage 5     ROUTER      classify intent, resolve client/product/sector\n"
        "                 |        deterministic keyword + entity matching\n"
        "                 v\n"
        "              RETRIEVAL   filter, rank and cap rows in pandas\n"
        "                 |        the model never decides a ranking\n"
        "                 v\n"
        "              CONTEXT     render selected rows; enumerate every figure\n"
        "                 |        token-budgeted, priority-ordered\n"
        "                 v\n"
        "              LLM         write prose over that context, and nothing else\n"
        "                 |\n"
        "                 v\n"
        "              VALIDATION  reject unsupported figures and banned claims\n"
        "                 |\n"
        "                 v\n"
        "              AUDIT       question, IDs, context, model, prompt version, answer\n"
        "                 |\n"
        "                 v\n"
        "              ANSWER\n"
        "```\n"
    )
    add(
        "**The path that does not exist:** raw CSV → LLM → financial calculation. No module "
        "under `src/syn_wallet/copilot/` can reach a raw dataset. Retrieval reads exactly "
        f"{len(REQUIRED_TABLES)} tables, all of them stage 3 or stage 4 outputs:\n"
    )
    add("".join(f"- `{name}.parquet`\n" for name in REQUIRED_TABLES))

    # ================================================================ Routing
    add("## 3. Routing\n")
    add(
        f"{len(router.INTENTS)} intents, resolved by keyword and entity matching over a fixed "
        f"vocabulary of {len(copilot.clients)} clients, {len(router.PRODUCT_ALIASES)} products "
        f"and {len(router.SECTOR_ALIASES)} sectors. Nothing here is learned or fuzzy.\n"
    )
    add(
        "Deterministic routing buys three things. Retrieval stays cheap and auditable — the "
        "audit log records exactly which entities were pulled. The model never sees a client the "
        "banker did not ask about, so it cannot quote one. And routing still works with no API "
        "key, which is what makes the offline mode a real answer rather than an error page.\n"
    )

    rows = []
    for label, question in USE_CASES:
        route, retrieved, bundle = copilot.plan(question)
        rows.append(
            {
                "Use case": label,
                "Example question": f"“{question}”",
                "Routed intent": f"`{route.intent}`",
                "Resolved": ", ".join(
                    filter(
                        None,
                        [
                            ", ".join(route.entity_ids),
                            ", ".join(route.products),
                            ", ".join(route.sectors),
                        ],
                    )
                )
                or "portfolio-wide",
                "Context tokens": f"{bundle.token_estimate:,}",
                "Figures": len(bundle.figures),
            }
        )
    add(table(pd.DataFrame(rows)))
    largest = max(rows, key=lambda row: int(row["Context tokens"].replace(",", "")))
    add(
        f"Every context sits inside the {config.MAX_CONTEXT_TOKENS:,}-token budget with room to "
        f"spare. The largest here is the {largest['Use case'].lower()} at "
        f"{largest['Context tokens']} tokens — roughly "
        f"{int(largest['Context tokens'].replace(',', '')) / config.MAX_CONTEXT_TOKENS:.0%} of "
        "budget.\n"
    )

    add("### Ambiguity and failure\n")
    add(
        "- **A client outside the portfolio** — “Prepare a briefing for Sasol” — is detected and "
        "reported. Without that check it would fall through to a portfolio query and the banker "
        "would get a confident answer to a question they did not ask.\n"
        "- **An off-topic question** — “What is the weather in Johannesburg?” — carries no "
        "client, product, sector or banking vocabulary, and is declined rather than answered.\n"
        "- **An article is never a client name.** “The Bidvest Group” is indexed on `bidvest`, "
        "not on `the`; indexing on the article made E18 match almost every question asked and "
        "silently poisoned every downstream retrieval.\n"
    )

    # ============================================================== Retrieval
    add("## 4. Retrieval\n")
    add(
        "Deterministic filtering first, always. *“Which mining clients have the strongest "
        "trade-finance opportunities?”* is:\n"
    )
    add(
        "```\n"
        "filter opportunity_selection_detail\n"
        "  where product = 'trade_finance'\n"
        "    and sector  = 'mining'\n"
        "    and opportunity_status <> 'NO_HEADROOM_DEMONSTRATED'\n"
        "sort by selection_score desc, entity_id asc\n"
        "head(limit)\n"
        "then join: explanations, sensitivity, diagnostics for exactly those rows\n"
        "```\n"
    )
    add(
        "The ranking is the model's, not the language model's. If the LLM were asked to rank, "
        "the ranking would be unverifiable and would silently disagree with the numbers printed "
        "next to it.\n"
    )
    add(
        "Rows where the model could not demonstrate headroom are excluded from ranked answers. "
        "A fully-served pillar is not a small opportunity, it is a different statement, and "
        "mixing the two would mislead.\n"
    )

    # ================================================================ Context
    add("## 5. Context\n")
    add(
        "Rendered as labelled lines rather than tables or JSON — one fact per line, units "
        "attached. Figures are **pre-formatted**, so the model copies `R8.75tn` rather than "
        "rendering a number itself.\n"
    )
    add(
        "Sections, in priority order. Trimming drops from the end, so client figures survive and "
        "background goes first:\n"
    )
    add(
        "1. `RETRIEVAL NOTES` — anything the retriever could not do\n"
        "2. `CLIENTS` — profile, selected slots, diagnostics summary\n"
        "3. `PILLAR FIGURES` — observed, addressable, share, opportunity, confidence, status, "
        "sensitivity range, per pillar\n"
        "4. `BANKER QUESTIONS` — pre-written by stage 4, with rationales\n"
        "5. `MODEL EXPLANATIONS` — the deterministic six-part explanation\n"
        "6. `PORTFOLIO METRICS`\n"
        "7. `MODEL DIAGNOSTICS` — HIGH severity first\n"
        "8. `HOW THE MODEL WORKS` — the methodology notes for this intent\n"
    )
    add(
        "Every rand and percentage written into the context is also recorded in an allow-list. "
        "That list is what validation checks the answer against, and building it at render time "
        "from the same strings the model sees is the only way to make the check exact.\n"
    )

    # ============================================================= Guardrails
    add("## 6. Guardrails\n")
    add(
        "The prompt is a request. The check is a guarantee. Both are in place, and the check is "
        "the one that is tested.\n"
    )
    add("### Before the model\n")
    add(
        "- The model receives only retrieved rows. It cannot see another client, another "
        "product, or any raw data.\n"
        "- Every figure it might need is already computed and formatted.\n"
        f"- {len(validation.FORBIDDEN_PHRASES)} banned phrases are inherited verbatim from the "
        "commercial intelligence layer, so the two can never drift apart.\n"
    )
    add("### After the model\n")
    add(
        "| Check | What it catches |\n|---|---|\n"
        "| Unsupported figure | Any rand or percentage not in the context allow-list — including "
        "a cross-pillar total, which by construction was never produced upstream |\n"
        "| Forbidden phrase | `fee pool`, `bank revenue`, `competitor-held`, `confirmed "
        "revenue`, `i calculate`, `total across all pillars`, and the rest |\n"
        "| Share attribution | A share of wallet attached to lending or investment banking, by "
        "proximity with negation awareness |\n"
        "| Investment-banking rand | Any rand amount attached to the signal-only pillar |\n"
    )
    add(
        "A failing answer is **discarded, not patched**. The banker gets the deterministic "
        "answer plus a notice saying the AI answer was rejected, and the violation goes to the "
        "audit log — so a reviewer can measure how often the model misbehaved rather than "
        "trusting that it did not.\n"
    )

    # =============================================================== Fallback
    add("### Providers and configuration\n")
    add(
        "| Provider | Endpoint | Key variable | Default model | Note |\n|---|---|---|---|---|\n"
        + "".join(
            f"| `{provider.name}` | `{provider.base_url}` | `{provider.key_env}` | "
            f"`{provider.default_model}` | {provider.note} |\n"
            for provider in config.PROVIDERS.values()
        )
    )
    add(
        "Both speak the OpenAI chat-completions protocol, so one client class covers both and "
        "only the endpoint, key and model name differ. A provider is chosen by "
        "`SYN_COPILOT_PROVIDER`, or automatically as the first one whose key is present.\n"
    )
    add(
        "Configuration lives in `.env`, which is gitignored; `.env.example` is the committed "
        "template and a test asserts it carries no real key and names every variable the code "
        "reads. A value already set in the shell wins over the file, so a one-off override needs "
        "no edit. Confirm what a key can actually reach with "
        "`python -m src.syn_wallet.ask --list-models` rather than trusting a constant — model "
        "names move faster than documentation.\n"
    )

    add("## 7. Working without an API key\n")
    add(
        "Judging happens on someone else's laptop, on conference wifi, possibly with no key. A "
        "copilot that shows an error in that moment has failed regardless of how good it is when "
        "the network works.\n"
    )
    modes = pd.DataFrame(
        [
            {
                "Mode": f"`{mode}`",
                "When": when,
                "Notice shown to the banker": (
                    config.MODE_NOTICE[mode][:110] + "…"
                    if len(config.MODE_NOTICE[mode]) > 110
                    else config.MODE_NOTICE[mode]
                )
                or "none — this is a normal generated answer",
            }
            for mode, when in (
                (config.LLM, "The model answered and the answer passed validation"),
                (config.DEMO, "No key, but this exact question has a stored demo answer"),
                (config.FALLBACK_NO_KEY, "No key and no stored answer"),
                (config.FALLBACK_ERROR, "The service could not be reached"),
                (
                    config.FALLBACK_TRUNCATED,
                    "The service answered, but the answer exceeded the output budget",
                ),
                (config.FALLBACK_VALIDATION, "The answer failed validation and was discarded"),
            )
        ]
    )
    add(table(modes))
    add(
        f"**{len(library)} stored demo answers** are committed to "
        "`data/processed/copilot_demos.json`, generated once against the live model and checked "
        "before storing. Each records the digest of the context it was generated from, so a demo "
        "that has drifted from the current model outputs can be detected rather than quietly "
        "shown.\n"
    )
    add(
        "The deterministic fallback is not a stub. Stage 4 already generated six-part "
        "explanations and client-specific questions for every client x pillar, so the fallback "
        "assembles genuine content — it simply reads less fluently. **The figures are identical "
        "either way**, which is the whole point: the language model was never the thing "
        "producing them.\n"
    )

    # =========================================================== Auditability
    add("## 8. Auditability\n")
    add(
        "Every answer writes one JSON line to an append-only log. In a bank, *the model said so* "
        "is not an answer to a compliance question.\n"
    )
    add(
        "| Field | Contents |\n|---|---|\n"
        "| `record_id`, `timestamp_utc` | Identity and time |\n"
        "| `query` | The banker's question, verbatim |\n"
        "| `intent`, `route` | What the router decided, and what it matched on |\n"
        "| `entity_ids`, `products` | Exactly what was retrieved |\n"
        "| `retrieval` | Row counts per table, plus any retriever notes |\n"
        "| `context` | The full context block the model was given |\n"
        "| `settings` | Model name, base URL, temperature, top_p, seed, prompt version |\n"
        "| `validation` | The verdict, every violation, and the rejected answer if there was one |\n"
        "| `answer`, `mode`, `latency_seconds` | What was returned and how |\n"
    )
    add(
        "**No secret is ever written.** The key is read from the environment at call time, is "
        "not on the settings object, and `_assert_no_secret` inspects every record before it is "
        "serialised — checking both for credential-shaped keys and for the key's own value, so a "
        "future edit cannot quietly land it in a log file. A test asserts it.\n"
    )

    # ================================================================ Testing
    add("## 9. Testing\n")
    add(
        "Every copilot test runs **offline**, with the language model replaced by a fake that "
        "returns whatever the test tells it to. That is the only way to assert what happens when "
        "a model misbehaves — you cannot ask a real one to hallucinate on cue.\n"
    )
    add(
        "| Area | What is asserted |\n|---|---|\n"
        "| Hallucination resistance | An invented figure, a cross-pillar total, a competitor "
        "claim, a fee-pool phrase and a lending share are each caught, discarded and logged |\n"
        "| Client retrieval | A client question retrieves that client and no other name reaches "
        "the model |\n"
        "| Product retrieval | Sector and product filters are applied before generation |\n"
        "| Sensitivity retrieval | Ranges match `opportunity_sensitivity_summary` exactly |\n"
        "| Confidence retrieval | Bands and scores match `opportunity_selection_detail` |\n"
        "| Terminology | No forbidden phrase in any context or any fallback answer, for every "
        "use case |\n"
        "| Figures | Every figure in every fallback answer appears in that answer's context |\n"
        "| Fallback | No key, service error, validation failure and stored demo all produce a "
        "usable answer |\n"
        "| Invalid input | Empty questions raise; off-topic questions are declined |\n"
        "| Missing client | A name outside the portfolio is reported, not guessed |\n"
        "| Audit | Required fields present, retrieved IDs recorded, no key-shaped string |\n"
        "| Determinism | Identical questions produce identical contexts and identical answers |\n"
    )

    # =============================================================== Limits
    add("## 10. What this layer deliberately does not do\n")
    add(
        "- **It does not calculate.** Not a sum, not a percentage, not a rank. Every number is "
        "read from a stage 3 or stage 4 output.\n"
        "- **It does not remember.** Each question is answered from scratch, with no "
        "conversation history. A follow-up must name its subject.\n"
        "- **It does not search.** There is no vector store and no embedding model. With 20 "
        "clients, 5 pillars and a fixed vocabulary, exact filtering is both cheaper and more "
        "accurate than similarity search, and it is auditable.\n"
        "- **It does not act.** No writes, no emails, no CRM updates.\n"
        "- **It cannot make a figure up and get away with it.** It can still write an awkward "
        "sentence, and the fallback can read stiffly.\n"
    )
    add("### The boundary of the figure check\n")
    add(
        "Validation catches an **invented** figure. It does not catch a **misattributed** one, "
        "and that distinction was observed rather than theorised. Asked *“How reliable is the "
        "Vodacom Group FX opportunity?”*, a weaker model on the same endpoint wrote:\n"
    )
    add(
        "> The estimate … is LOW in confidence, with a base case of **R7.89bn**. However, this "
        "figure is SENSITIVE to benchmark assumptions, ranging from R3.09bn to R15.13bn …\n"
    )
    add(
        "Every one of those figures is in the context. But R7.89bn is the *opportunity*; the "
        "range belongs to the *addressable* figure, whose base is R10.97bn. The sentence is "
        "built entirely from real numbers and is still wrong, and no string-matching check can "
        "see it.\n"
    )
    add(
        "Three things reduce the exposure, and none eliminates it. The context labels each "
        "figure explicitly (`Opportunity:`, `addressable figure … around a base of`) rather than "
        "leaving the model to infer roles. The primary model is the more careful one — the same "
        "question answered correctly on `z-ai/glm-5.2`. And there is deliberately **no automatic "
        "fallback to a different model**: a weaker model's answer would pass the figure check and "
        "ship a misattribution, whereas the deterministic fallback is merely less fluent. When "
        "the primary model is unavailable, being stiff is better than being wrong.\n"
    )

    # ================================================== Worked examples
    add("## 11. Worked examples\n")
    if len(library) == 0:
        add(
            "_No stored demo answers yet. Run "
            "`NVIDIA_API_KEY=... python -m src.syn_wallet.build_copilot_demos --overwrite`._\n"
        )
    else:
        add(
            f"{len(library)} answers generated against the live model, validated, and committed "
            "to `data/processed/copilot_demos.json`. Every figure in them came from the "
            "deterministic layers; the model only wrote the prose. Reproduced here verbatim.\n"
        )
        for demo in sorted(library.all(), key=lambda answer: answer.title):
            heading = demo.title or demo.intent
            add(f"### {heading}\n")
            add(f"**Question:** “{demo.question}”\n")
            if demo.note:
                add(f"*Why this example:* {demo.note}\n")
            add(
                f"*Routed to* `{demo.intent}`"
                + (f", retrieved `{', '.join(demo.entity_ids)}`" if demo.entity_ids else "")
                + f". Generated by `{demo.model}` on prompt `{demo.prompt_version}`; "
                f"validation checked {demo.validation.get('checked_figures', 0)} figures against "
                "the context and passed.\n"
            )
            add("---\n")
            add(demo.answer.strip() + "\n")
            add("---\n")

    add("## 12. Reproduce\n")
    add(
        "```bash\n"
        "# stages 1-4 first (see README)\n"
        "cp .env.example .env                 # then set DEEPSEEK_API_KEY (optional)\n"
        "python -m src.syn_wallet.ask --list-models                 # confirm the model name\n"
        "python -m src.syn_wallet.build_copilot_demos --overwrite   # stored demo answers\n"
        "python -m analysis.genai_prompts_report                    # -> docs/GENAI_PROMPTS.md\n"
        "python -m analysis.genai_design_report                     # -> docs/GENAI_DESIGN.md\n"
        "python -m pytest tests/test_copilot.py\n"
        "```\n"
    )
    add(
        "```python\n"
        "from src.syn_wallet.copilot.engine import Copilot\n"
        "\n"
        "copilot = Copilot.from_processed()\n"
        'answer = copilot.ask("Which mining clients have the strongest trade-finance '
        'opportunities?")\n'
        "print(answer.rendered())      # the answer, with its mode notice\n"
        "print(answer.mode)            # llm / demo_stored_response / fallback_*\n"
        "print(answer.entity_ids)      # exactly what it was allowed to see\n"
        "```\n"
    )

    return "\n".join(sections)


def main() -> None:
    write(REPORT_PATH, build_report())


if __name__ == "__main__":
    main()
