"""Generate ``docs/MODEL_FINAL_REPORT.md`` -- the stable analytical contract.

This is the document the application layer is built against. It states the final
methodology, the final terminology, every formula, and -- the part that matters
most for a dashboard -- what may and may not be put on a screen.

    .venv/bin/python -m src.syn_wallet.build_wallet --overwrite --sensitivity
    .venv/bin/python -m analysis.model_final_report
"""

from __future__ import annotations

import pandas as pd

from src.syn_wallet import config
from src.syn_wallet.wallet import assumptions, benchmarks, confidence, contract, opportunity

from .report_common import connect, model_report, table, write

REPORT_PATH = config.REPOSITORY_ROOT / "docs" / "MODEL_FINAL_REPORT.md"

TABLES = (
    "opportunity_engine",
    "client_opportunity_profile",
    "product_classification",
    "product_confidence",
    "portfolio_summary",
    "model_benchmarks",
    "model_benchmark_metrics",
    "model_diagnostics",
    "wallet_estimates",
    "model_sensitivity_robustness",
    "model_sensitivity_by_product",
    "client_features",
)


def build_report() -> str:
    connection = connect(TABLES)
    report = model_report()
    sections: list[str] = []
    add = sections.append

    add("# Syn Bank Share of Wallet Engine — Final Model Report\n")
    add(
        f"Methodology `{assumptions.METHODOLOGY_VERSION}`. {report['clients']} clients x "
        f"{len(report['products'])} pillars = {report['estimate_rows']} estimates. "
        "**This document is the analytical contract.** Everything downstream — dashboard, "
        "generated narrative, any export — reads the two published tables described in section 10 "
        "and nothing else.\n"
    )
    add(
        "Generated by `analysis/model_final_report.py` from `data/processed/*.parquet`. Not "
        "hand-edited. Companion documents: `docs/MODEL_SENSITIVITY.md` (36-scenario sweep), "
        "`docs/MODEL_REPORT.md` (worked examples and per-client derivations), `docs/AUDIT_REPORT.md` (data "
        "quality), `CLAUDE.md` (source-of-truth totals).\n"
    )

    # ================================================================ 1. Hierarchy
    add("## 1. Product hierarchy\n")
    add(
        "Share of Wallet is a claim about a denominator: *of the activity this client must "
        "transact somewhere, what fraction runs through Syn Bank*. Three pillars can support that "
        "claim. Two cannot, and calling their output a share would mean inventing the "
        "denominator.\n"
    )
    classes = connection.execute(
        "SELECT product, product_class FROM product_classification"
    ).df().set_index("product")["product_class"]
    hierarchy = pd.DataFrame(
        [
            {
                "Pillar": f"{position}. {assumptions.PRODUCT_LABELS[product]}",
                "Role": assumptions.PILLAR_ROLE[product].replace("_", " "),
                "Class": classes[product],
                "What it publishes": {
                    assumptions.CASH: "addressable cash flow, observed, share, opportunity",
                    assumptions.FX: "peer-benchmark addressable, observed, share, opportunity",
                    assumptions.TRADE: "peer-benchmark addressable, observed, share, opportunity",
                    assumptions.LENDING: "a rand financing need. **No share.**",
                    assumptions.IB: "a ranked signal and a category. **No rand, no share.**",
                }[product],
            }
            for position, product in enumerate(assumptions.PRODUCTS, start=1)
        ]
    )
    add(table(hierarchy))
    add(
        f"**{assumptions.PILLAR_ROLE_NOTES[assumptions.OPPORTUNITY_SIGNAL]}** No lending share of "
        "wallet and no investment-banking share of wallet is computed anywhere in this engine, "
        "and a test asserts that none can appear.\n"
    )

    # ============================================================= 2. Terminology
    add("## 2. Terminology\n")
    add(
        "Naming discipline, because the wrong noun is a commercial claim. The single most likely "
        "misreading of this deck is that a fourteen-trillion-rand cash figure is money a bank "
        "could earn. It is not, and the schema is built so nobody can read it that way.\n"
    )
    terminology = pd.DataFrame(
        [{"Column": f"`{name}`", "What it means": note}
         for name, note in assumptions.TERMINOLOGY.items()]
    )
    add(table(terminology))
    add(
        "**Preferred phrasing throughout: \"Addressable Cash Flow\" or \"Cash Management "
        "Addressable Flow\".** Never \"cash management wallet\", never \"revenue opportunity\", "
        "never \"fee pool\". `cash_management_wallet_zar` exists as a named, permanently NULL "
        "column so that the fee wallet is visibly absent rather than an omission a reader fills "
        "in with the flow figure.\n"
    )

    # ================================================================ 3. Formulae
    add("## 3. Formulae\n")
    add("### Pillar 1 — Transactional / Cash Management\n")
    add(
        "```\n"
        "addressable_cash_flow_zar = revenue_total_zar + cost_of_sales_zar\n"
        "                            ^ collections        ^ supplier payments\n"
        "                            (identity: revenue   (identity: cost of sales\n"
        "                             is collected into    is paid out of a\n"
        "                             a bank account)      bank account)\n"
        "\n"
        "observed_zar = domestic collections + domestic supplier payments, fiscal year\n"
        "share        = observed_zar / addressable_cash_flow_zar\n"
        "opportunity_zar = addressable_cash_flow_zar - observed_zar   (floored at 0)\n"
        "\n"
        "cash_management_wallet_zar = NULL     -- no disclosed pricing, never derived\n"
        "```\n"
    )
    add(
        "Both coefficients are 1.0 on an accounting-identity basis, so **no scenario in the "
        "sensitivity grid can move this pillar**. Payroll, tax and intercompany sweeps are "
        "excluded from *both* sides and carried separately as mandate signals: no external field "
        "sizes them, and putting an invented denominator opposite a token numerator would "
        "manufacture a fake gap. The excluded amount is published per client as "
        "`out_of_scope_observed_zar`. SWIFT-channel volume is excluded from this numerator and "
        "not added to FX either, so no rand is counted twice in either direction.\n"
    )

    add("### Pillar 2 — FX / Global Markets\n")
    add(
        "```\n"
        "export_settlement = foreign_revenue_zar x peer_p75(xb_inbound / revenue_foreign)\n"
        "import_settlement = cost_of_sales_zar  x peer_p75(xb_outbound / cost_of_sales)\n"
        "hedging_execution = fx_forward_notional_zar x 1.0 roll\n"
        "addressable_zar   = export + import + hedging      (floored at observed)\n"
        "observed_zar      = cross-border volume, fiscal year\n"
        "```\n"
    )
    add("### Pillar 3 — Trade Finance\n")
    add(
        "```\n"
        "import_documentary = cost_of_sales_zar  x peer_p75(tf_import / cost_of_sales)\n"
        "export_documentary = foreign_revenue_zar x peer_p75(tf_export / revenue_foreign)\n"
        "guarantees         = revenue_total_zar   x peer_p75(tf_guarantees / revenue)\n"
        "addressable_zar    = the applicable components  (floored at observed)\n"
        "observed_zar       = instruments dated in the fiscal year, all four statuses\n"
        "```\n"
    )
    add(
        "Import and export documentary sub-models are **suppressed entirely** for insurance and "
        "real estate: an insurer buys no goods and a property group holds no tradeable inventory. "
        "Only the guarantee sub-model applies there, and applicability drops to 0.30, which pushes "
        "confidence into LOW.\n"
    )
    add("### Pillar 4 — Lending (opportunity signal, no share)\n")
    add(
        "```\n"
        "refinancing        = debt_current_zar          x 1.0   (structural)\n"
        "undrawn_facilities = undrawn_facilities_zar    x 1.0   (structural)\n"
        "working_capital    = working_capital_zar       x peer_median(debt_current / wc)\n"
        "capex_funding      = capex_zar                 x 0.30  (JUDGEMENT)\n"
        "opportunity_zar    = the sum of the above\n"
        "share              = NULL -- no loan book exists in the supplied data\n"
        "```\n"
    )
    add("### Pillar 5 — Investment Banking (signal only, no rand)\n")
    add(
        "```\n"
        "signal_score = 0.20 scale + 0.25 leverage + 0.25 near_term_maturity\n"
        "             + 0.20 capex_intensity + 0.10 syndicate_breadth\n"
        "               (each a percentile rank inside this portfolio)\n"
        "addressable_zar = NULL,  opportunity_zar = NULL,  share = NULL\n"
        "```\n"
    )

    # ======================================================= 4. Benchmark method
    add("## 4. Benchmark methodology\n")
    add(
        "Where no accounting identity fixes a coefficient it is **measured, not invented**: the "
        "75th-percentile observed intensity across the client's peers. Two rules make that "
        "defensible rather than merely plausible.\n"
    )
    add("### 4.1 Leave-one-out\n")
    add(
        "**The client being estimated is excluded from the population that sets its own "
        "coefficient.** Including it is circular in both directions: a heavily penetrated client "
        "raises the benchmark it is then measured against, flattening its own gap; a dormant "
        "client drags the benchmark down and makes its own share look healthy. With twenty "
        "clients one company is 5% of the portfolio and up to a third of its sector, so this is a "
        "material correction. `PeerBenchmarks.leave_one_out_p75(client_id, metric)` is the "
        "primitive, and tests assert directly on the populations that no client appears in its "
        "own.\n"
    )
    add("### 4.2 Sector before portfolio, with a hard floor on sample size\n")
    add(
        "```\n"
        "IF the client's sector has >= 3 peer observations AFTER excluding the client:\n"
        "    use the sector P75\n"
        "ELSE:\n"
        "    use the portfolio P75 (itself requiring >= 4 contributors after exclusion)\n"
        "IF neither population is large enough:\n"
        "    publish no coefficient -- the component is NULL, never a borrowed number\n"
        "```\n"
    )
    add(
        f"`MIN_SECTOR_SAMPLE_FOR_BENCHMARK = {benchmarks.MIN_SECTOR_SAMPLE_FOR_BENCHMARK}`, "
        f"`MIN_BENCHMARK_SAMPLE = {benchmarks.MIN_BENCHMARK_SAMPLE}`. A sector benchmark built "
        "from one or two companies would be a restatement of those companies rather than a "
        "sector norm. Every client x metric coefficient records `benchmark_level`, "
        "`benchmark_n`, `benchmark_value`, `benchmark_median`, `benchmark_p75`, `benchmark_max` "
        "and `fallback_reason`, so any single estimate can be reconstructed from "
        "`model_benchmarks.parquet`.\n"
    )
    add("### 4.3 Which population each metric actually used\n")
    levels = connection.execute(
        """
        SELECT m.metric AS "Metric", m.product AS "Pillar",
               m.population_n AS "Portfolio population",
               COUNT(*) FILTER (WHERE b.benchmark_level = 'sector') AS "Clients on sector",
               COUNT(*) FILTER (WHERE b.benchmark_level = 'portfolio') AS "Clients on portfolio",
               COUNT(*) FILTER (WHERE b.benchmark_level = 'unavailable') AS "No coefficient",
               printf('%.4f', m.population_p75) AS "Population P75"
        FROM model_benchmark_metrics m
        JOIN model_benchmarks b ON b.metric = m.metric
        WHERE m.metric <> 'cash_cogs_to_revenue_imputation'
        GROUP BY 1, 2, 3, 7 ORDER BY 2, 1
        """
    ).df()
    add(table(levels))
    add(
        "The two foreign-revenue metrics land on the portfolio for every client, and that is the "
        "sector rule working rather than failing: only nine of twenty clients disclose foreign "
        "revenue at all, spread across six sectors with at most two each, so no sector can reach "
        "three peers. The rule declines to build a sector benchmark precisely where it would have "
        "been one or two companies.\n"
    )
    add(
        "> **The driver-imputation cascade is leave-one-out by construction, not by "
        "enforcement.** Where a client does not disclose cost of sales or foreign revenue, the "
        "value is imputed from a sector median. Only clients that *disclosed* the field "
        "contribute to that median, and only clients that did *not* disclose it consume one, so a "
        "client can never impute its own driver from itself.\n"
    )

    # ======================================================= 5. Confidence method
    add("## 5. Confidence methodology\n")
    add(
        "Four factors describe how good the **inputs** are and combine additively. A fifth, "
        "`evidence_directness`, describes how sound the **method** is and *multiplies* that "
        "total, so it caps confidence rather than being outvoted by it. An earlier additive "
        "version scored all twenty investment-banking estimates HIGH — a pillar whose every "
        "threshold is an undrawn judgement — purely because the balance-sheet fields behind it "
        "were fully disclosed.\n"
    )
    weights = pd.DataFrame(
        [{"Factor": f"`{name}`", "Weight": f"{weight:.2f}", "Combines": "additive"}
         for name, weight in confidence.WEIGHTS.items()]
        + [{"Factor": "`evidence_directness`", "Weight": "x", "Combines": "**multiplicative**"}]
    )
    add(table(weights))
    add(
        "Basis directness: accounting identity 1.00, structural 0.90, peer benchmark 0.60, "
        f"judgement 0.35. Scaled down further when a component could not be built at all, and "
        f"halved when the wallet had to be floored at observed activity. Bands: HIGH at "
        f"{assumptions.CONFIDENCE_BAND_HIGH:.2f}, MEDIUM at "
        f"{assumptions.CONFIDENCE_BAND_MEDIUM:.2f}, LOW below.\n"
    )
    add("### Product confidence summary\n")
    product_confidence = connection.execute(
        """
        SELECT product_label AS "Pillar", product_class AS "Class",
               printf('%.3f', mean_confidence) AS "Mean",
               printf('%.3f', median_confidence) AS "Median",
               printf('%.0f%%', 100 * pct_high) AS "HIGH",
               printf('%.0f%%', 100 * pct_medium) AS "MEDIUM",
               printf('%.0f%%', 100 * pct_low) AS "LOW",
               printf('%.0f%%', 100 * pct_major_diagnostic) AS "Major flag"
        FROM product_confidence
        ORDER BY CASE product
            WHEN 'cash_management' THEN 1 WHEN 'fx_global_markets' THEN 2
            WHEN 'trade_finance' THEN 3 WHEN 'lending' THEN 4 ELSE 5 END
        """
    ).df()
    add(table(product_confidence))
    add(
        "\"Major flag\" is the fraction of clients carrying at least one **HIGH-severity** "
        "diagnostic for that pillar — the *do not quote before review* class, not the merely "
        "noteworthy one.\n"
    )
    add(
        "> **The confidence spread is itself the model's most important finding about itself.** "
        "Cash management averages 0.86 with 80% HIGH because it rests on identities. FX and trade "
        "average 0.35 and 0.34 with 70% and 85% LOW, because they rest on peer coefficients "
        "applied to partly imputed drivers. A dashboard that shows the FX rand figure at the same "
        "visual weight as the cash rand figure is misrepresenting the model.\n"
    )

    # ================================================= 6. Product classification
    add("## 6. Product classification\n")
    add(
        "Assigned **by measurement at build time**, not hardcoded, so a future run in which the "
        "lending data gained an observed numerator would reclassify itself rather than silently "
        "contradict a dashboard:\n"
    )
    add(
        "```\n"
        "no rand estimate for anybody          -> SIGNAL_ONLY\n"
        "rand estimate but no computable share -> SUPPORTING\n"
        f"share computable for >= {opportunity.CORE_SHARE_COVERAGE:.0%} of clients   -> CORE\n"
        "```\n"
    )
    classification = connection.execute(
        """
        SELECT product_label AS "Pillar", product_class AS "Class",
               clients_with_estimate AS "With rand", clients_with_share AS "With share",
               classification_reason AS "Why"
        FROM product_classification
        ORDER BY CASE product
            WHEN 'cash_management' THEN 1 WHEN 'fx_global_markets' THEN 2
            WHEN 'trade_finance' THEN 3 WHEN 'lending' THEN 4 ELSE 5 END
        """
    ).df()
    add(table(classification))

    # ================================================ 7. Opportunity ranking
    add("## 7. Opportunity ranking methodology\n")
    add(
        "Two rankings, because bankers ask two different questions. **They disagree, and they are "
        "meant to. Show both; never average them.**\n"
    )
    add("### A. Commercial Opportunity Score — *where is the largest opportunity?*\n")
    add(
        "```\n"
        f"commercial_opportunity_score = {assumptions.OPPORTUNITY_WEIGHTS['gap']:.2f} x "
        "gap_percentile_within_product\n"
        f"                             + {assumptions.OPPORTUNITY_WEIGHTS['confidence']:.2f} x "
        "confidence\n"
        f"                             + {assumptions.OPPORTUNITY_WEIGHTS['headroom']:.2f} x "
        "(1 - share)\n"
        "```\n"
    )
    add(
        "Percentile rather than raw rand, so a trillion-rand revenue base cannot dominate on "
        "scale alone and the five different estimate bases stay comparable. Confidence is in the "
        "score so a large opportunity resting on an imputed denominator ranks below a smaller one "
        "built from disclosures. Headroom is neutral at 0.5 where no share exists, rather than "
        "rewarding or penalising a number that does not exist.\n"
    )
    add("### B. Opportunity Intensity — *where are we most obviously absent?*\n")
    add(
        "```\n"
        "opportunity_intensity = opportunity_zar / addressable_cash_flow_zar\n"
        "```\n"
    )
    add(
        "**No weights and no fitted coefficients at all.** One denominator per client — the "
        "client's own addressable cash flow — which is identity-anchored, available for all "
        "twenty, and identical across the five pillars, so a client's five intensities are "
        "directly comparable to each other. This is what lets a small company with a "
        "proportionally enormous gap outrank a giant with a proportionally small one, which the "
        "within-product percentile in the commercial score cannot do.\n"
    )
    add("### Where they disagree\n")
    disagree = connection.execute(
        """
        SELECT entity_name AS "Client", product AS "Pillar",
               commercial_rank AS "Commercial rank", intensity_rank AS "Intensity rank",
               zar(opportunity_zar) AS "Opportunity",
               printf('%.2f', opportunity_intensity) AS "Intensity"
        FROM opportunity_engine
        WHERE intensity_rank IS NOT NULL
          AND ABS(commercial_rank - intensity_rank) >= 25
        ORDER BY intensity_rank LIMIT 8
        """
    ).df()
    add(table(disagree))
    add(
        "> **Shaftesbury Capital's lending position is the metric earning its place.** Its "
        "financing need is 3.86x its entire annual operating cash flow — the most "
        "disproportionate position in the portfolio — and the commercial score buries it at rank "
        "67 because the rand amount is small next to Glencore's. Both rankings are right about "
        "different questions.\n"
    )

    # ============================================== 8. Sensitivity findings
    add("## 8. Sensitivity findings\n")
    add(
        "Full detail in `docs/MODEL_SENSITIVITY.md`: 36 full model runs across benchmark statistic "
        "(median / P75 / P80), leave-one-out versus self-inclusive populations, sector versus "
        "portfolio scope, and capex debt-funded share (0.20 / 0.30 / 0.40).\n"
    )
    robustness = connection.execute(
        """
        SELECT product_label AS "Pillar", verdict AS "Verdict",
               printf('%.3f', min_spearman_rank_in_product) AS "Worst rank rho",
               CASE WHEN max_abs_total_gap_drift IS NULL THEN 'no rand figure'
                    ELSE printf('%.0f%%', 100 * max_abs_total_gap_drift) END AS "Worst drift"
        FROM model_sensitivity_robustness WHERE product <> 'ALL'
        ORDER BY CASE product
            WHEN 'cash_management' THEN 1 WHEN 'fx_global_markets' THEN 2
            WHEN 'trade_finance' THEN 3 WHEN 'lending' THEN 4 ELSE 5 END
        """
    ).df()
    add(table(robustness))
    spread = connection.execute(
        """
        SELECT product_label AS "Pillar", zar(MIN(total_gap_zar)) AS "Lowest",
               zar(MAX(total_gap_zar)) AS "Highest",
               printf('%.1fx', MAX(total_gap_zar) / NULLIF(MIN(total_gap_zar), 0)) AS "Ratio"
        FROM model_sensitivity_by_product WHERE total_gap_zar IS NOT NULL
        GROUP BY product, product_label
        ORDER BY CASE product
            WHEN 'cash_management' THEN 1 WHEN 'fx_global_markets' THEN 2
            WHEN 'trade_finance' THEN 3 WHEN 'lending' THEN 4 ELSE 5 END
        """
    ).df()
    add(table(spread))
    add(
        "**Robust:** cash management (untouched by every scenario), lending (rho >= 0.997, under "
        "5% drift), the identity of the top ten (9 or 10 of 10 survive every scenario), and the "
        "investment-banking signal ordering.\n\n"
        "**Assumption-sensitive:** the FX and trade rand totals, which span 7.4x and 4.0x across "
        "the grid. This is not a defect — it is the honest consequence of having no disclosed "
        "total for either activity, so the denominator *is* the coefficient. Rank these; quote "
        "the range, never a single number.\n"
    )

    # ================================================== 9. Results
    add("## 9. Results\n")
    add("### 9.1 Portfolio position by pillar\n")
    summary = connection.execute(
        """
        SELECT product_label AS "Pillar", product_class AS "Class",
               zar(total_observed_zar) AS "Observed", zar(total_estimate_zar) AS "Addressable",
               zar(total_gap_zar) AS "Opportunity",
               CASE WHEN portfolio_share IS NULL THEN 'no share'
                    ELSE printf('%.2f%%', 100 * portfolio_share) END AS "Share",
               printf('%.2f', mean_confidence) AS "Mean conf"
        FROM portfolio_summary
        ORDER BY CASE product
            WHEN 'cash_management' THEN 1 WHEN 'fx_global_markets' THEN 2
            WHEN 'trade_finance' THEN 3 WHEN 'lending' THEN 4 ELSE 5 END
        """
    ).df()
    add(table(summary))
    add(
        "> **These five rows must never be added together.** 279,389 transactional rows sit on "
        "the SWIFT channel and overlap cross-border payments by an amount the supplied fields "
        "cannot resolve; the five bases are not commensurable; and lending has no observed side "
        "at all. There is no total, and a build-time assertion prevents one appearing in the "
        "client profile table.\n"
    )

    add("### 9.2 Top 20 by Commercial Opportunity Score\n")
    top_commercial = connection.execute(
        """
        SELECT commercial_rank AS "#", entity_name AS "Client", product AS "Pillar",
               printf('%.3f', commercial_opportunity_score) AS "Score",
               zar(opportunity_zar) AS "Opportunity",
               CASE WHEN share IS NULL THEN 'n/a' ELSE printf('%.2f%%', 100 * share) END AS "Share",
               confidence_band AS "Conf",
               CASE WHEN high_severity_diagnostic THEN 'REVIEW' ELSE '' END AS "Flag"
        FROM opportunity_engine ORDER BY commercial_rank LIMIT 20
        """
    ).df()
    add(table(top_commercial))

    add("### 9.3 Top 20 by Opportunity Intensity\n")
    top_intensity = connection.execute(
        """
        SELECT intensity_rank AS "#", entity_name AS "Client", product AS "Pillar",
               printf('%.3f', opportunity_intensity) AS "Intensity",
               zar(opportunity_zar) AS "Opportunity",
               zar(addressable_cash_flow_zar) AS "Client cash flow",
               confidence_band AS "Conf", commercial_rank AS "Comm. rank"
        FROM opportunity_engine WHERE intensity_rank IS NOT NULL
        ORDER BY intensity_rank LIMIT 20
        """
    ).df()
    add(table(top_intensity))
    add(
        "> **This list is dominated by cash management, and that is a property of the metric, not "
        "a finding.** For the cash pillar the intensity ratio reduces to `1 - share` exactly, and "
        "Syn Bank's cash share is under half a percent for every client, so every cash row scores "
        "0.91-1.00. The discrimination lives *within* each pillar. **Use "
        "`intensity_rank_in_product` for prioritisation, or filter to one pillar.** The two rows "
        "that beat cash — Shaftesbury and NEPI Rockcastle on lending, at 3.86 and 1.11 — are the "
        "genuine cross-pillar signals, both property groups whose financing need exceeds their "
        "operating turnover.\n"
    )

    add("### 9.4 Intensity within each pillar, where the metric discriminates\n")
    per_pillar_intensity = connection.execute(
        """
        SELECT product AS "Pillar", intensity_rank_in_product AS "#",
               entity_name AS "Client", printf('%.4f', opportunity_intensity) AS "Intensity",
               zar(opportunity_zar) AS "Opportunity", confidence_band AS "Conf"
        FROM opportunity_engine
        WHERE product <> 'cash_management' AND intensity_rank_in_product <= 4
        ORDER BY product, intensity_rank_in_product
        """
    ).df()
    add(table(per_pillar_intensity))

    add("### 9.5 Large opportunities on low confidence\n")
    add(
        "The rows most likely to be quoted and least likely to survive review. The commercial "
        "score already discounts them, but the rand amounts must not be quoted without the "
        "caveat.\n"
    )
    low_confidence = connection.execute(
        f"""
        SELECT entity_name AS "Client", product AS "Pillar",
               zar(opportunity_zar) AS "Opportunity", printf('%.2f', confidence) AS "Conf",
               benchmark_level AS "Benchmark", benchmark_n AS "n",
               commercial_rank AS "Comm. rank"
        FROM opportunity_engine
        WHERE confidence < {assumptions.CONFIDENCE_BAND_MEDIUM} AND opportunity_zar IS NOT NULL
        ORDER BY opportunity_zar DESC LIMIT 10
        """
    ).df()
    add(table(low_confidence))

    add("### 9.6 Diagnostics\n")
    diagnostics_summary = connection.execute(
        """
        SELECT severity AS "Severity", COUNT(*) AS "Findings",
               COUNT(DISTINCT diagnostic) AS "Distinct checks"
        FROM model_diagnostics GROUP BY severity
        ORDER BY CASE severity WHEN 'HIGH' THEN 1 WHEN 'MEDIUM' THEN 2 ELSE 3 END
        """
    ).df()
    add(table(diagnostics_summary))
    top_diagnostics = connection.execute(
        """
        SELECT diagnostic AS "Diagnostic", severity AS "Severity", COUNT(*) AS "Rows"
        FROM model_diagnostics GROUP BY 1, 2 ORDER BY 3 DESC LIMIT 10
        """
    ).df()
    add(table(top_diagnostics))

    # ============================================== 10. The contract
    add("## 10. The analytical contract\n")
    add(
        "Two published tables. Downstream code may read these columns and should tolerate "
        "additional ones being appended; it must never rely on ordinal position.\n"
    )
    add("### `data/processed/opportunity_engine.parquet`\n")
    add(
        f"**Grain: one row per client x product.** {report['clients']} x "
        f"{len(report['products'])} = {report['estimate_rows']} rows.\n"
    )
    columns = pd.DataFrame(
        {"Column": [f"`{name}`" for name in contract.OPPORTUNITY_ENGINE_COLUMNS]}
    )
    add(
        "```\n"
        + "\n".join(
            ", ".join(contract.OPPORTUNITY_ENGINE_COLUMNS[position : position + 4])
            for position in range(0, len(contract.OPPORTUNITY_ENGINE_COLUMNS), 4)
        )
        + "\n```\n"
    )
    del columns
    add(
        "**NULL policy, enforced and tested:** a product with no defensible rand denominator "
        "keeps NULL in every rand column. Never zero. *We cannot size this* and *this is worth "
        "nothing* are opposite statements, and a `fillna(0)` anywhere downstream would merge "
        "them. Investment banking is NULL in `observed_zar`, `addressable_zar` and "
        "`opportunity_zar` for all twenty clients, and publishes `signal_score` instead.\n"
    )
    add("### `data/processed/client_opportunity_profile.parquet`\n")
    add(
        "**Grain: one row per client.** Each pillar's headline side by side: addressable cash "
        "flow and cash share, FX addressable and share, trade addressable and share, lending "
        "opportunity, IB signal, both scores, confidence, major diagnostics, top opportunity and "
        "the recommended next product to investigate.\n"
    )
    add(
        "**No column sums the pillars, and none can be added.** `assert_no_pillar_summation` runs "
        "at every build and fails loudly if any column equals the row-wise total of the pillar "
        "columns.\n"
    )
    add(
        "The *recommended next product* is deterministic: the client's second-highest commercial "
        "opportunity score among the pillars that produce a rand figure, excluding the top "
        "opportunity itself. Investment banking is never recommended — it would send a banker to "
        "a page with no number on it.\n"
    )

    # ============================================== 11. Limitations
    add("## 11. Model limitations\n")
    add(
        "- **The FX and trade rand figures are peer-benchmark, not disclosed totals.** No "
        "disclosure states either activity's true size, so the denominator is the coefficient. "
        "They span 7.4x and 4.0x across the sensitivity grid. Rank them; state the range.\n"
        "- **If the whole portfolio is under-penetrated, every peer-benchmark wallet is "
        "understated together** and no amount of internal data would reveal it. The benchmark "
        "client is near 100% share by construction.\n"
        "- **`capex_debt_funded_share = 0.30` is the one underived coefficient in the engine.** "
        "Moving it by a third in either direction moves the lending total under 5%, and a "
        "diagnostic fires wherever it drives more than half of a client's estimate.\n"
        "- **Opportunity intensity is near-degenerate for cash management**, where it reduces to "
        "`1 - share` and every client scores 0.91-1.00. Use `intensity_rank_in_product`.\n"
        "- **The cash ranking is close to a size ranking.** That is the honest consequence of an "
        "identity-anchored denominator — the biggest payment flows really are the biggest "
        "opportunities — but the ordering carries little client-specific information beyond "
        "scale, and a `product_ranking_tracks_company_size` diagnostic says so in the data.\n"
        "- **Nine of twenty clients report in a currency other than ZAR** and are converted at "
        "SARB rates averaged over each entity's own fiscal-year window. A different FX basis "
        "would move their figures; the three prepared rate sources agree to within 0.85%.\n"
        "- **Fiscal year ends span nine months across five distinct dates**, so \"the fiscal "
        "year\" is not one window across the portfolio. Cross-client rand comparisons carry that "
        "caveat.\n"
        "- **Three clients fail the revenue-split identity and several disclose an unverifiable "
        "zero debt.** Both are carried through as flags rather than corrected.\n"
        "- **Four clients disclose no cost of sales**, so their supplier-payment and import "
        "components rest on a peer ratio applied to revenue.\n"
        "- **No pricing, anywhere.** Every figure is a flow or balance magnitude. Nothing in this "
        "engine is bank revenue, fee income, or margin.\n"
        "- **A gap is addressable business not observed in Syn Bank's supplied data.** It is "
        "never evidence that a competitor holds it.\n"
    )

    # ============================================== 12. Dashboard rules
    add("## 12. What the dashboard should and should not show\n")
    add("### Show\n")
    add(
        "- **Share of wallet for the three CORE pillars**, each with its confidence band next to "
        "it. Cash at HIGH confidence may be a headline; FX and trade at 70% and 85% LOW must "
        "carry their band in the same visual unit as the number.\n"
        "- **Addressable Cash Flow**, under that name, with the fee wallet visibly absent.\n"
        "- **Both rankings side by side**, labelled with the question each answers.\n"
        "- **`benchmark_level` and `benchmark_n`** wherever an FX or trade figure appears. \"P75 "
        "of 4 mining peers, this client excluded\" is the sentence that makes the number "
        "defensible.\n"
        "- **The `explanation` string**, which is generated per row and already names every "
        "driver, coefficient, population and caveat behind the figure.\n"
        "- **Diagnostic count and the HIGH-severity flag** on every row.\n"
        "- **The sensitivity range on FX and trade totals**, not a point estimate.\n"
        "- **Lending as a rand opportunity with no share**, labelled SUPPORTING.\n"
        "- **Investment banking as a ranked signal and a category**, labelled SIGNAL_ONLY.\n"
    )
    add("### Do not show\n")
    add(
        "- **Any total across the five pillars.** Not a portfolio wallet, not a client total, not "
        "a stacked bar whose segments are the five pillars. The transactional and cross-border "
        "pillars overlap by an unresolvable amount.\n"
        "- **Any lending or investment-banking share of wallet.** Neither exists; both are NULL "
        "by design.\n"
        "- **Any rand figure for investment banking.**\n"
        "- **Any fee, margin, basis-point or revenue figure.** There is no pricing in this "
        "repository and none may be inferred.\n"
        "- **A zero where the model published NULL.** Charting libraries default missing to zero; "
        "they must be configured not to. *Not estimable* and *zero* are opposite claims.\n"
        "- **FX or trade rand amounts as headline numbers without their confidence band and "
        "range.**\n"
        "- **The cross-pillar intensity leaderboard as a prioritisation tool** — it is dominated "
        "by cash by construction. Rank intensity within a pillar.\n"
        "- **A gap described as \"competitor-held\", \"lost revenue\" or \"win-back\".** It is "
        "addressable activity not observed in the supplied data.\n"
    )

    add("## 13. Reproduce\n")
    add(
        "```bash\n"
        "tar -xzf data/data.tgz -C data/\n"
        ".venv/bin/python -m src.syn_wallet.clean_data --overwrite\n"
        ".venv/bin/python -m src.syn_wallet.build_features --overwrite\n"
        ".venv/bin/python -m src.syn_wallet.build_wallet --overwrite --sensitivity\n"
        ".venv/bin/python -m analysis.model_sensitivity_report\n"
        ".venv/bin/python -m analysis.model_final_report\n"
        ".venv/bin/python -m pytest\n"
        "```\n"
    )
    add(
        "The engine is deterministic: identical inputs produce byte-identical outputs, and tests "
        "assert it for the estimates, the contract tables and the sensitivity sweep.\n"
    )

    connection.close()
    return "\n".join(sections)


def main() -> None:
    write(REPORT_PATH, build_report())


if __name__ == "__main__":
    main()
