"""Generate ``docs/MODEL_REPORT.md`` from the wallet engine's actual outputs.

The report is written, not typed. Every figure in it is read back from
``data/processed/*.parquet``, so it cannot claim a coefficient the engine does
not use or a result the engine did not produce. Regenerate it whenever the model
changes::

    .venv/bin/python -m analysis.wallet_model_report
"""

from __future__ import annotations

import json
import duckdb
import pandas as pd

from src.syn_wallet import config
from src.syn_wallet.wallet import assumptions, confidence, engine

REPORT_PATH = config.REPOSITORY_ROOT / "docs" / "MODEL_REPORT.md"


def _connect() -> duckdb.DuckDBPyConnection:
    connection = duckdb.connect(":memory:")
    tables = [
        "wallet_estimates",
        "opportunities",
        "wallet_components",
        "model_diagnostics",
        "portfolio_summary",
        "model_assumptions",
        "model_benchmarks",
        "model_benchmark_metrics",
        "product_classification",
        "product_confidence",
        "model_sector_rules",
        "client_features",
    ]
    # Rand at a scale a reader can hold in their head: a portfolio cash wallet
    # of R14,284.58bn reads as noise, R14.28tn does not.
    connection.execute(
        "CREATE MACRO zar(value) AS CASE "
        "WHEN value IS NULL THEN 'n/a' "
        "WHEN ABS(value) >= 1e12 THEN printf('R%.2ftn', value / 1e12) "
        "WHEN ABS(value) >= 1e9 THEN printf('R%.2fbn', value / 1e9) "
        "WHEN ABS(value) >= 1e6 THEN printf('R%.1fm', value / 1e6) "
        "ELSE printf('R%.0f', value) END"
    )
    for name in tables:
        path = config.PROCESSED_DIR / f"{name}.parquet"
        if not path.is_file():
            raise FileNotFoundError(
                f"Missing {path}. Run `python -m src.syn_wallet.build_wallet --overwrite` first."
            )
        connection.execute(f"CREATE VIEW {name} AS SELECT * FROM read_parquet('{path}')")
    return connection


def _table(frame: pd.DataFrame) -> str:
    """Render a DataFrame as a GitHub-flavoured markdown table."""
    if frame.empty:
        return "_None._\n"
    header = "| " + " | ".join(str(column) for column in frame.columns) + " |"
    divider = "|" + "|".join("---" for _ in frame.columns) + "|"
    rows = [
        "| " + " | ".join("" if pd.isna(value) else str(value) for value in row) + " |"
        for row in frame.itertuples(index=False)
    ]
    return "\n".join([header, divider, *rows]) + "\n"


def build_report() -> str:
    connection = _connect()
    report = json.loads((config.PROCESSED_DIR / "model_report.json").read_text(encoding="utf-8"))
    examples = json.loads(
        (config.PROCESSED_DIR / "worked_examples.json").read_text(encoding="utf-8")
    )

    sections: list[str] = []
    add = sections.append

    add(f"# Syn Bank Share of Wallet Engine — Model Report\n")
    add(
        f"Methodology version `{report['methodology_version']}`. "
        f"{report['clients']} clients x {len(report['products'])} product pillars = "
        f"{report['estimate_rows']} estimates. Every figure below is read back from "
        "`data/processed/*.parquet`; this file is generated by "
        "`analysis/wallet_model_report.py` and is not hand-edited.\n"
    )

    # ---------------------------------------------------------------- Methodology
    add("## Methodology\n")
    add(
        "Five product pillars, each with its own economic model and its own denominator. "
        "The pillars are never summed: the transactional and cross-border datasets overlap on "
        "SWIFT-channel rows by an amount the supplied fields cannot resolve.\n"
    )
    add(
        "For every client and pillar the engine separates **observed** activity (what is visible "
        "in Syn Bank's data), the **addressable wallet or opportunity** (what could reasonably be "
        "served), **share**, **gap**, and **confidence**. A gap is addressable business not "
        "observed in Syn Bank's supplied data. It is never described as confirmed "
        "competitor-held business.\n"
    )
    basis = pd.DataFrame(
        [
            {
                "Pillar": assumptions.PRODUCT_LABELS[product],
                "Estimate basis": f"`{assumptions.ESTIMATE_BASIS[product]}`",
                "What the denominator is": assumptions.ESTIMATE_BASIS_NOTES[
                    assumptions.ESTIMATE_BASIS[product]
                ],
            }
            for product in assumptions.PRODUCTS
        ]
    )
    add(_table(basis))
    add(
        "> **The two bases are not comparable as rand.** Cash management is anchored on an "
        "accounting identity, so its wallet is the client's whole disclosed payment flow across "
        "all banks. FX and trade finance have no disclosed total, so their wallets are the "
        "client's own driver scaled by the intensity a well-penetrated peer achieves. Cash gaps "
        "are consequently orders of magnitude larger. The opportunity score ranks on "
        "within-pillar percentiles precisely so these bases are never compared directly.\n"
    )

    # -------------------------------------------------------------------- Formula
    add("## Formula\n")
    add("### 1. Transactional / Cash Management\n")
    add(
        "```\n"
        "wallet = collections + supplier_payments\n"
        "       = revenue_total_zar x 1.0        (identity: revenue is collected into a bank)\n"
        "       + cost_of_sales_zar x 1.0        (identity: cost of sales is paid out of one)\n"
        "observed = domestic-channel collections + domestic-channel supplier payments (fiscal year)\n"
        "```\n"
    )
    add(
        "Payroll, tax and intercompany sweeps are excluded from **both** sides. No employee-cost "
        "or tax-charge field exists, and treasury sweep volume has no external anchor; including "
        "observed sweeps against a denominator that cannot cover them would inflate share. The "
        "excluded activity is published as `out_of_scope_observed_zar`. Payroll survives as a "
        "*mandate signal* — instructions per employee — because observed payroll is a token R61m "
        "portfolio-wide at R11,048 an instruction.\n"
    )
    add("### 2. FX / Global Markets\n")
    add(
        "```\n"
        "wallet = export_settlement + import_settlement + hedging_execution\n"
        "       = foreign_revenue_basis x peer_P75(xb_inbound / foreign_revenue)\n"
        "       + cost_of_sales_basis  x peer_P75(xb_outbound / cost_of_sales)\n"
        "       + fx_forward_notional  x 1.0     (one roll, a deliberate floor)\n"
        "observed = cross-border payment volume (fiscal year)\n"
        "```\n"
    )
    add(
        "Foreign revenue is an **exposure** variable, never equated with settlement volume: MTN's "
        "Nigerian revenue is collected in naira inside Nigeria and never crosses a border. The "
        "exposure-to-volume conversion is measured from the client's peers -- the client itself is "
        "excluded from the population that sets its own coefficient. Directions are split so "
        "inbound and outbound demand cannot double count.\n"
    )
    add("### 3. Trade Finance\n")
    add(
        "```\n"
        "wallet = import_documentary + export_documentary + guarantees\n"
        "       = cost_of_sales_basis  x peer_P75(tf_import / cost_of_sales)     [suppressed: insurance, real_estate]\n"
        "       + foreign_revenue_basis x peer_P75(tf_export / foreign_revenue)  [suppressed: insurance, real_estate]\n"
        "       + revenue_total_zar     x peer_P75(tf_guarantees / revenue)      [all sectors]\n"
        "observed = instruments dated in the fiscal year, all four statuses (annual issuance)\n"
        "```\n"
    )
    add("### 4. Lending\n")
    add(
        "```\n"
        "opportunity = refinancing + undrawn_facilities + working_capital + capex_funding\n"
        "            = debt_current_zar        x 1.0   (structural: repayable within 12 months)\n"
        "            + undrawn_facilities_zar  x 1.0   (structural: committed, unused headroom)\n"
        "            + max(working_capital, 0) x median(debt_current / working_capital)\n"
        "            + capex_zar               x 0.30  (JUDGEMENT)\n"
        "share = NULL — Syn Bank's datasets contain no loan book\n"
        "```\n"
    )
    add(
        "Gross debt is never used as the estimate: existing debt is not assumed replaceable. The "
        "output is named an *opportunity estimate*, not a wallet, and no share is claimed.\n"
    )
    add("### 5. Investment Banking / Capital Markets\n")
    add(
        "```\n"
        "signal = 0.20 scale + 0.25 leverage + 0.25 near_term_maturity\n"
        "       + 0.20 capex_intensity + 0.10 syndicate_breadth   (all percentile ranks)\n"
        "estimate_zar = NULL — no rand amount is produced\n"
        "```\n"
    )
    add(
        "A category is assigned only when a specific disclosure threshold is met, and "
        "`none_supported` is a legitimate and common answer.\n"
    )
    ib_categories = connection.execute(
        """
        SELECT opportunity_type AS "Category", COUNT(*) AS "Clients",
               string_agg(entity_id, ', ' ORDER BY entity_id) AS "Who"
        FROM wallet_estimates WHERE product = 'investment_banking'
        GROUP BY 1 ORDER BY 2 DESC
        """
    ).df()
    add(_table(ib_categories))

    # --------------------------------------------------------------------- Inputs
    add("## Inputs\n")
    drivers = connection.execute(
        """
        SELECT product AS "Pillar", component AS "Component",
               COUNT(*) FILTER (WHERE driver_source = 'disclosed') AS "Disclosed",
               COUNT(*) FILTER (WHERE driver_source = 'sector_benchmark') AS "Sector-imputed",
               COUNT(*) FILTER (WHERE driver_source = 'portfolio_benchmark') AS "Portfolio-imputed",
               COUNT(*) FILTER (WHERE driver_source = 'unavailable') AS "Unavailable"
        FROM wallet_components
        WHERE product <> 'investment_banking'
        GROUP BY 1, 2 ORDER BY 1, 2
        """
    ).df()
    add(
        "How each component's economic driver was resolved across the 20 clients. A driver is "
        "resolved through a cascade — disclosed value, then sector peer ratio, then portfolio "
        "ratio — and is **never imputed to zero**. Insurance and real estate are barred from "
        "cost-of-sales imputation entirely, because their cost line is not a procurement proxy.\n"
    )
    add(_table(drivers))

    # ---------------------------------------------------------------- Assumptions
    add("## Assumptions\n")
    add(
        "Every coefficient is declared in `src/syn_wallet/wallet/assumptions.py` with a basis "
        "saying where its authority comes from. Nothing numeric lives in the pillar models.\n"
    )
    static = connection.execute(
        """
        SELECT basis AS "Basis", name AS "Name", value AS "Value", product AS "Product",
               rationale AS "Rationale"
        FROM model_assumptions WHERE value IS NOT NULL
        ORDER BY CASE basis WHEN 'accounting_identity' THEN 0 WHEN 'structural' THEN 1
                            WHEN 'portfolio_benchmark' THEN 2 ELSE 3 END, name
        """
    ).df()
    add(_table(static))
    add("### Deliberate exclusions\n")
    excluded = connection.execute(
        """
        SELECT name AS "Name", product AS "Product", rationale AS "Why it is excluded"
        FROM model_assumptions WHERE value IS NULL ORDER BY name
        """
    ).df()
    add(_table(excluded))
    add("### Coefficients measured from this portfolio\n")
    add(
        "These are not chosen, they are measured at build time from the feature table and "
        "rewritten on every run. Each is the 75th percentile of observed intensity across the "
        "client's **peers** — 'what a well-penetrated peer achieves' — except the working-capital "
        "ratio, which uses the median because it is a structural funding norm rather than a "
        "penetration frontier. **The client being estimated is always excluded from the "
        "population that sets its own coefficient**, and a sector population is used wherever it "
        "reaches three peers after that exclusion, so the coefficient differs per client. "
        "`model_benchmarks.parquet` carries one row per client x metric; the table below "
        "summarises the populations behind them. See `docs/MODEL_FINAL_REPORT.md` section 4.\n"
    )
    benchmarks = connection.execute(
        """
        SELECT metric AS "Metric", product AS "Pillar",
               ROUND(population_p75, 6) AS "Population P75", population_n AS "n",
               ROUND(population_median, 6) AS "Population median",
               ROUND(population_max, 6) AS "Population max",
               clients_on_sector_benchmark AS "On sector",
               clients_on_portfolio_benchmark AS "On portfolio",
               numerator AS "Numerator", denominator AS "Denominator"
        FROM model_benchmark_metrics ORDER BY product, metric
        """
    ).df()
    add(_table(benchmarks))
    add("### Sector treatment\n")
    sector_rules = connection.execute(
        """
        SELECT product AS "Pillar", sector AS "Sector", applicability AS "Applicability",
               suppressed_components AS "Sub-models switched off", note AS "Reason"
        FROM model_sector_rules WHERE applicability < 1.0 OR suppressed_components <> ''
        ORDER BY product, sector
        """
    ).df()
    add(
        "Sectors not listed use the base methodology unchanged. A sector-specific adjustment is "
        "only made where the economic logic genuinely differs.\n"
    )
    add(_table(sector_rules))

    # ---------------------------------------------------------------- Confidence
    add("## Confidence\n")
    add(
        "Four factors describe input quality and combine additively. A fifth — "
        "`evidence_directness`, how sound the *method* is — then **multiplies** that total, so "
        "having every input a model needs cannot make a weak model confident.\n"
    )
    add(
        "```\n"
        "input_quality = "
        + " + ".join(f"{weight:.2f} x {name}" for name, weight in confidence.WEIGHTS.items())
        + "\n"
        "confidence    = input_quality x evidence_directness\n"
        "```\n"
    )
    directness = pd.DataFrame(
        [
            {"Coefficient basis": name, "Directness": value}
            for name, value in confidence.BASIS_DIRECTNESS.items()
        ]
    )
    add(_table(directness))
    add(
        f"Directness is scaled further by the fraction of expected components that could actually "
        f"be built, and halved again when a wallet had to be floored at observed activity. Bands: "
        f"HIGH at {assumptions.CONFIDENCE_BAND_HIGH:.2f}, MEDIUM at "
        f"{assumptions.CONFIDENCE_BAND_MEDIUM:.2f}, LOW below.\n"
    )
    add(
        "> **A consequence worth stating.** FX and trade finance rest on peer benchmarks, whose "
        "directness is capped at 0.60, so **neither pillar can reach HIGH confidence by "
        "construction**. That is a real property of a model with no disclosed total to divide by, "
        "not an accident of calibration.\n"
    )
    bands = connection.execute(
        """
        SELECT product AS "Pillar", ROUND(AVG(confidence), 2) AS "Mean",
               ROUND(MIN(confidence), 2) AS "Min", ROUND(MAX(confidence), 2) AS "Max",
               COUNT(*) FILTER (WHERE confidence_band = 'HIGH') AS "HIGH",
               COUNT(*) FILTER (WHERE confidence_band = 'MEDIUM') AS "MEDIUM",
               COUNT(*) FILTER (WHERE confidence_band = 'LOW') AS "LOW"
        FROM wallet_estimates GROUP BY 1
        ORDER BY CASE product WHEN 'cash_management' THEN 0 WHEN 'fx_global_markets' THEN 1
                              WHEN 'trade_finance' THEN 2 WHEN 'lending' THEN 3 ELSE 4 END
        """
    ).df()
    add(_table(bands))

    # --------------------------------------------------------- Opportunity score
    add("## Opportunity score\n")
    weights = assumptions.OPPORTUNITY_WEIGHTS
    add(
        "```\n"
        f"opportunity_score = {weights['gap']:.2f} x gap_scale "
        f"+ {weights['confidence']:.2f} x confidence "
        f"+ {weights['headroom']:.2f} x headroom\n"
        "\n"
        "gap_scale = percentile rank of the rand gap WITHIN its product\n"
        "            (investment banking contributes its signal score instead)\n"
        "headroom  = 1 - share, or a neutral 0.5 where no defensible share exists\n"
        "```\n"
    )
    add(
        "Percentile rather than raw rand for two reasons: the five pillars have different "
        "estimate bases that must not be compared as one number, and rank is what stops a "
        "trillion-rand revenue base from dominating on scale alone. Confidence at 0.30 pushes "
        "large opportunities resting on imputed denominators down the ranking rather than "
        "silently promoting them.\n"
    )

    # --------------------------------------------------------------- Diagnostics
    add("## Diagnostics\n")
    add(
        "Model weaknesses are published as data in `model_diagnostics.parquet`, at client, "
        "product and sector scope. HIGH means do not use the number before review.\n"
    )
    findings = connection.execute(
        """
        SELECT severity AS "Severity", diagnostic AS "Diagnostic", COUNT(*) AS "Findings"
        FROM model_diagnostics GROUP BY 1, 2
        ORDER BY CASE severity WHEN 'HIGH' THEN 0 WHEN 'MEDIUM' THEN 1 ELSE 2 END, 3 DESC
        """
    ).df()
    add(_table(findings))
    add("### Known model weaknesses\n")
    scoped = connection.execute(
        """
        SELECT severity AS "Severity", COALESCE(product, '') AS "Pillar",
               COALESCE(sector, '') AS "Sector", diagnostic AS "Diagnostic",
               ROUND(metric_value, 4) AS "Metric", detail AS "Detail"
        FROM model_diagnostics WHERE scope <> 'client_product'
        ORDER BY CASE severity WHEN 'HIGH' THEN 0 WHEN 'MEDIUM' THEN 1 ELSE 2 END, product
        """
    ).df()
    add(_table(scoped))

    # ------------------------------------------------------------------- Results
    add("## Results\n")
    add("### Portfolio by pillar\n")
    summary = connection.execute(
        """
        SELECT product_label AS "Pillar",
               zar(total_observed_zar) AS "Observed",
               zar(total_estimate_zar) AS "Estimate",
               zar(total_gap_zar) AS "Gap",
               CASE WHEN portfolio_share IS NULL THEN 'n/a'
                    ELSE printf('%.3f%%', portfolio_share * 100) END AS "Portfolio share",
               CASE WHEN median_client_share IS NULL THEN 'n/a'
                    ELSE printf('%.2f%%', median_client_share * 100) END AS "Median client share",
               ROUND(mean_confidence, 2) AS "Mean confidence"
        FROM portfolio_summary
        ORDER BY CASE product WHEN 'cash_management' THEN 0 WHEN 'fx_global_markets' THEN 1
                              WHEN 'trade_finance' THEN 2 WHEN 'lending' THEN 3 ELSE 4 END
        """
    ).df()
    add(_table(summary))
    add(
        "The gap between portfolio share and median client share is the size effect: the "
        "value-weighted share is dragged down by the largest clients, where Syn Bank's "
        "penetration is thinnest.\n"
    )
    add("### Top 15 opportunities\n")
    top = connection.execute(
        """
        SELECT rank_overall AS "#", entity_name AS "Client", sector AS "Sector",
               product AS "Pillar",
               zar(estimate_zar) AS "Wallet",
               CASE WHEN "share" IS NULL THEN 'n/a' ELSE printf('%.2f%%', "share" * 100) END AS "Share",
               zar(gap_zar) AS "Gap",
               confidence_band AS "Confidence",
               printf('%.3f', opportunity_score) AS "Score"
        FROM opportunities ORDER BY rank_overall LIMIT 15
        """
    ).df()
    add(_table(top))
    add("### Where there is no headroom left\n")
    bottom = connection.execute(
        """
        SELECT rank_overall AS "#", entity_name AS "Client", product AS "Pillar",
               zar(gap_zar) AS "Gap",
               printf('%.1f%%', "share" * 100) AS "Share",
               confidence_band AS "Confidence", diagnostic_flags AS "Flags"
        FROM opportunities WHERE "share" >= 0.999 ORDER BY rank_overall DESC
        """
    ).df()
    add(
        "These are the clients where the model cannot demonstrate headroom. In every case the "
        "modelled driver landed below activity already flowing and the wallet was floored — which "
        "is a statement about the model, not about the client.\n"
    )
    add(_table(bottom))
    add("### By sector\n")
    sectors = connection.execute(
        """
        SELECT sector AS "Sector", COUNT(DISTINCT entity_id) AS "Clients",
               zar(SUM(gap_zar)) AS "Gap (cash+FX+trade)",
               printf('%.2f%%', SUM(observed_zar) / SUM(estimate_zar) * 100) AS "Blended share",
               ROUND(AVG(confidence), 2) AS "Mean confidence"
        FROM wallet_estimates
        WHERE product IN ('cash_management', 'fx_global_markets', 'trade_finance')
        GROUP BY 1 ORDER BY SUM(gap_zar) DESC
        """
    ).df()
    add(_table(sectors))

    # ------------------------------------------------------------------ Examples
    add("## Examples\n")
    add(
        "Three clients, chosen to span the situations a reviewer most needs to see: a "
        "well-observed domestic retailer, a foreign-currency reporter whose drivers are largely "
        "imputed, and an insurer whose sector suppresses two sub-models. Every value is read "
        "back from the generated tables.\n"
    )
    for example in examples:
        add(engine.format_worked_example(example))

    # --------------------------------------------------------------- Limitations
    add("## Limitations\n")
    add(
        "**What this model does not claim.**\n\n"
        "- It does not price anything. Syn Bank is fictional and has no disclosed pricing, so "
        "  every figure is a flow or balance magnitude, never bank revenue. There is no fee, "
        "  margin or basis-point assumption anywhere in the engine.\n"
        "- It does not assert competitor ownership. A gap is addressable business not observed in "
        "  Syn Bank's supplied data. The absence of activity is not evidence that a competitor "
        "  holds it, and the presence of competitor-lending memos is evidence only that such "
        "  lending exists, not of its size.\n"
        "- It does not claim a lending or investment-banking share. Syn Bank's datasets contain "
        "  no loan book and no deal pipeline, so both are reported with a NULL share and an "
        "  explicit reason.\n"
        "- It does not sum the pillars. 279,389 SWIFT-channel transactional rows overlap the "
        "  cross-border dataset by an unresolvable amount. Those rows are excluded from the cash "
        "  numerator and not added to the FX numerator, so they are counted in neither; the "
        "  amount is published per client.\n"
        "- It does not fit a model to the data. Every estimate is transparent arithmetic over "
        "  declared assumptions and can be recomputed by hand from the component breakdown.\n"
        "- It does not impute a gap to zero. An undisclosed driver produces a NULL component and "
        "  a NULL share, never a confident zero.\n"
    )
    size_correlation = connection.execute(
        "SELECT ROUND(MAX(metric_value), 3) FROM model_diagnostics "
        "WHERE diagnostic = 'product_ranking_tracks_company_size'"
    ).fetchone()[0]
    add(
        "**Where it is weakest.**\n\n"
        f"- Cash-management gap ranks correlate {size_correlation} "
        "  with revenue ranks. The within-pillar ordering is close to a size ordering — the "
        "  honest consequence of an identity-anchored denominator, but it carries little "
        "  client-specific information beyond scale.\n"
        "- FX and trade-finance wallets are peer-benchmark, not disclosed totals. If the whole "
        "  portfolio is under-penetrated, every wallet is understated together and no amount of "
        "  internal data would reveal it.\n"
        "- `capex_debt_funded_share` at 0.30 is the one coefficient in the engine that could not "
        "  be derived. A diagnostic fires wherever it drives more than half a lending estimate.\n"
        "- Four clients disclose no cost of sales and two sectors disclose none at all, so their "
        "  supplier-payment and import components rest on a peer ratio applied to revenue.\n"
        "- Three clients fail the revenue-split identity and several disclose an unverifiable "
        "  zero debt; both are carried through as flags rather than corrected.\n"
    )

    connection.close()
    return "\n".join(sections)


def main() -> None:
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(build_report(), encoding="utf-8")
    print(f"wrote {REPORT_PATH} ({REPORT_PATH.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
